# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true

auto: true

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

restylers:
  - name: black
    arguments: ["-l120"]
  - name: isort
    arguments: ["--profile", "black", "--combine-as", "--atomic", "-l120", "-n"]
