# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: true

exclude:
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73

changed_paths:
  maximum: 1000
  outcome: error

auto: true

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - name: black
  - name: isort
