# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: steammessages_inventory.steamclient.proto
# plugin: python-betterproto
# Last updated 09/09/2021

from dataclasses import dataclass

import betterproto

from .msg import UnifiedMessage


class GetInventoryRequest(UnifiedMessage, um_name="Inventory.GetInventory"):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)


class Response(UnifiedMessage, um_name="Inventory.GetInventory"):
    etag: str = betterproto.string_field(1)
    removeditemids: list[int] = betterproto.uint64_field(2)
    item_json: str = betterproto.string_field(3)
    itemdef_json: str = betterproto.string_field(4)
    ticket: bytes = betterproto.bytes_field(5)
    replayed: bool = betterproto.bool_field(6)


class ExchangeItemRequest(UnifiedMessage, um_name="Inventory.ExchangeItem"):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)
    materialsitemid: list[int] = betterproto.uint64_field(3)
    materialsquantity: list[int] = betterproto.uint32_field(4)
    outputitemdefid: int = betterproto.uint64_field(5)


class GetEligiblePromoItemDefIDsRequest(UnifiedMessage, um_name="Inventory.GetEligiblePromoItemDefIDs"):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)


class GetEligiblePromoItemDefIDsResponse(UnifiedMessage, um_name="Inventory.GetEligiblePromoItemDefIDs"):
    itemdefids: list[int] = betterproto.uint64_field(1)


class AddItemRequest(UnifiedMessage, um_name="Inventory.AddPromoItem"):
    appid: int = betterproto.uint32_field(1)
    itemdefid: list[int] = betterproto.uint64_field(2)
    itempropsjson: list[str] = betterproto.string_field(3)
    steamid: int = betterproto.uint64_field(4)
    notify: bool = betterproto.bool_field(5)
    requestid: int = betterproto.uint64_field(6)
    trade_restriction: bool = betterproto.bool_field(7)
    is_purchase: bool = betterproto.bool_field(8)


class ModifyItemsRequest(UnifiedMessage, um_name="Inventory.SafeModifyItems"):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)
    updates: "list[ModifyItemsRequestItemPropertyUpdate]" = betterproto.message_field(3)
    timestamp: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ModifyItemsRequestItemPropertyUpdate(betterproto.Message):
    itemid: int = betterproto.uint64_field(1)
    remove_property: bool = betterproto.bool_field(2)
    property_name: str = betterproto.string_field(3)
    property_value_bool: bool = betterproto.bool_field(4)
    property_value_int: int = betterproto.int64_field(5)
    property_value_string: str = betterproto.string_field(6)
    property_value_float: float = betterproto.float_field(7)


class ConsumePlaytimeRequest(UnifiedMessage, um_name="Inventory.ConsumePlaytime"):
    appid: int = betterproto.uint32_field(1)
    itemdefid: int = betterproto.uint64_field(2)


class ConsumeItemRequest(UnifiedMessage, um_name="Inventory.ConsumeItem"):
    appid: int = betterproto.uint32_field(1)
    itemid: int = betterproto.uint64_field(2)
    quantity: int = betterproto.uint32_field(3)
    timestamp: str = betterproto.string_field(4)
    steamid: int = betterproto.uint64_field(5)
    requestid: int = betterproto.uint64_field(6)


class DevSetNextDropRequest(UnifiedMessage, um_name="Inventory.DevSetNextDrop"):
    appid: int = betterproto.uint32_field(1)
    itemdefid: int = betterproto.uint64_field(2)
    droptime: str = betterproto.string_field(3)


class SplitItemStackRequest(UnifiedMessage, um_name="Inventory.SplitItemStack"):
    appid: int = betterproto.uint32_field(1)
    itemid: int = betterproto.uint64_field(2)
    quantity: int = betterproto.uint32_field(3)
    steamid: int = betterproto.uint64_field(5)


class CombineItemStacksRequest(UnifiedMessage, um_name="Inventory.CombineItemStacks"):
    appid: int = betterproto.uint32_field(1)
    fromitemid: int = betterproto.uint64_field(2)
    destitemid: int = betterproto.uint64_field(3)
    quantity: int = betterproto.uint32_field(4)
    steamid: int = betterproto.fixed64_field(7)


class GetItemDefMetaRequest(UnifiedMessage, um_name="Inventory.GetItemDefMeta"):
    appid: int = betterproto.uint32_field(1)


class GetItemDefMetaResponse(UnifiedMessage, um_name="Inventory.GetItemDefMeta"):
    modified: int = betterproto.uint32_field(1)
    digest: str = betterproto.string_field(2)


class GetUserPurchaseInfoRequest(UnifiedMessage, um_name="Inventory.GetUserPurchaseInfo"):
    pass


class GetUserPurchaseInfoResponse(UnifiedMessage, um_name="Inventory.GetUserPurchaseInfo"):
    ecurrency: int = betterproto.int32_field(1)


class PurchaseInitRequest(UnifiedMessage, um_name="Inventory.PurchaseInit"):
    appid: int = betterproto.uint32_field(1)
    language: int = betterproto.int32_field(2)
    line_items: "list[PurchaseInitRequestLineItem]" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class PurchaseInitRequestLineItem(betterproto.Message):
    itemdefid: int = betterproto.uint64_field(1)
    quantity: int = betterproto.uint32_field(2)


class PurchaseInitResponse(UnifiedMessage, um_name="Inventory.PurchaseInit"):
    orderid: int = betterproto.uint64_field(1)
    transid: int = betterproto.uint64_field(2)


class PurchaseFinalizeRequest(UnifiedMessage, um_name="Inventory.PurchaseFinalize"):
    appid: int = betterproto.uint32_field(1)
    language: int = betterproto.int32_field(2)
    orderid: int = betterproto.uint64_field(3)


class InspectItemRequest(UnifiedMessage, um_name="Inventory.InspectItem"):
    itemdefid: int = betterproto.uint64_field(1)
    itemid: int = betterproto.fixed64_field(2)
    tags: str = betterproto.string_field(3)


class ClientNewItemsNotification(UnifiedMessage, um_name="InventoryClient.NotifyNewItems"):
    appid: int = betterproto.uint32_field(1)
    inventory_response: "Response" = betterproto.message_field(2)
