from . import (
    steammessages_base_pb2 as message_base,
    steammessages_clientserver_2_pb2 as client_server_2,
    steammessages_clientserver_friends_pb2 as client_server_friends,
    steammessages_clientserver_login_pb2 as client_server_login,
    steammessages_clientserver_pb2 as client_server
)
from .emsg import EMsg


protobufs = {
    EMsg.Multi: message_base.CMsgMulti,
    EMsg.ClientHeartBeat: client_server_login.CMsgClientHeartBeat,
    EMsg.ClientLogon: client_server_login.CMsgClientLogon,
    EMsg.ClientLogonGameServer: client_server_login.CMsgClientLogon,
    EMsg.ClientLogOnResponse: client_server_login.CMsgClientLogonResponse,
    EMsg.ClientLogOff: client_server_login.CMsgClientLogOff,
    EMsg.ClientLoggedOff: client_server_login.CMsgClientLoggedOff,
    EMsg.ClientUpdateMachineAuth: client_server_2.CMsgClientUpdateMachineAuth,
    EMsg.ClientUpdateMachineAuthResponse: client_server_2.CMsgClientUpdateMachineAuthResponse,
    EMsg.ClientNewLoginKey: client_server_login.CMsgClientNewLoginKey,
    EMsg.ClientNewLoginKeyAccepted: client_server_login.CMsgClientNewLoginKeyAccepted,
    EMsg.ClientRequestWebAPIAuthenticateUserNonce: client_server_login.CMsgClientRequestWebAPIAuthenticateUserNonce,
    EMsg.ClientRequestWebAPIAuthenticateUserNonceResponse: client_server_login.CMsgClientRequestWebAPIAuthenticateUserNonceResponse,
    EMsg.ClientCMList: client_server.CMsgClientCMList,
    EMsg.ClientItemAnnouncements: client_server_2.CMsgClientItemAnnouncements,
    EMsg.ClientRequestItemAnnouncements: client_server_2.CMsgClientRequestItemAnnouncements,
    EMsg.ClientCommentNotifications: client_server_2.CMsgClientCommentNotifications,
    EMsg.ClientRequestCommentNotifications: client_server_2.CMsgClientRequestCommentNotifications,
    EMsg.ClientUserNotifications: client_server_2.CMsgClientUserNotifications,
    EMsg.ClientChatOfflineMessageNotification: client_server_2.CMsgClientOfflineMessageNotification,
    EMsg.ClientChatRequestOfflineMessageCount: client_server_2.CMsgClientRequestOfflineMessageCount,
    EMsg.ClientGamesPlayed: client_server.CMsgClientGamesPlayed,
    EMsg.ClientGamesPlayedWithDataBlob: client_server.CMsgClientGamesPlayed,
    EMsg.ClientAccountInfo: client_server_login.CMsgClientAccountInfo,
    EMsg.ClientEmailAddrInfo: client_server_2.CMsgClientEmailAddrInfo,
    EMsg.ClientIsLimitedAccount: client_server.CMsgClientIsLimitedAccount,
    EMsg.ClientWalletInfoUpdate: client_server.CMsgClientWalletInfoUpdate,
    EMsg.ClientLicenseList: client_server.CMsgClientLicenseList,
    # EMsg.ClientServiceMethod: CMsgClientServiceMethod,  TODO find these
    # EMsg.ClientServiceMethodResponse: CMsgClientServiceMethodResponse,
    EMsg.ClientGMSServerQuery: client_server_2.CMsgClientGMSServerQuery,
    EMsg.GMSClientServerQueryResponse: client_server_2.CMsgGMSClientServerQueryResponse,
    EMsg.ClientPICSChangesSinceRequest: client_server.CMsgClientPICSChangesSinceRequest,
    EMsg.ClientPICSChangesSinceResponse: client_server.CMsgClientPICSChangesSinceResponse,
    EMsg.ClientPICSProductInfoRequest: client_server.CMsgClientPICSProductInfoRequest,
    EMsg.ClientPICSProductInfoResponse: client_server.CMsgClientPICSProductInfoResponse,
    EMsg.ClientPICSAccessTokenRequest: client_server.CMsgClientPICSAccessTokenRequest,
    EMsg.ClientPICSAccessTokenResponse: client_server.CMsgClientPICSAccessTokenResponse,
    EMsg.EconTrading_InitiateTradeRequest: client_server_2.CMsgTrading_InitiateTradeRequest,
    EMsg.EconTrading_InitiateTradeResponse: client_server_2.CMsgTrading_InitiateTradeResponse,
    EMsg.EconTrading_CancelTradeRequest: client_server_2.CMsgTrading_CancelTradeRequest,
    EMsg.EconTrading_InitiateTradeProposed: client_server_2.CMsgTrading_InitiateTradeRequest,
    EMsg.EconTrading_InitiateTradeResult: client_server_2.CMsgTrading_InitiateTradeResponse,
    EMsg.EconTrading_StartSession: client_server_2.CMsgTrading_StartSession,
    EMsg.ClientChangeStatus: client_server_friends.CMsgClientChangeStatus,
    EMsg.ClientAddFriend: client_server_friends.CMsgClientAddFriend,
    EMsg.ClientAddFriendResponse: client_server_friends.CMsgClientAddFriendResponse,
    EMsg.ClientRemoveFriend: client_server_friends.CMsgClientRemoveFriend,
    EMsg.ClientFSGetFriendsSteamLevels: client_server_2.CMsgClientFSGetFriendsSteamLevels,
    EMsg.ClientFSGetFriendsSteamLevelsResponse: client_server_2.CMsgClientFSGetFriendsSteamLevelsResponse,
    EMsg.ClientPersonaState: client_server_friends.CMsgClientPersonaState,
    EMsg.ClientClanState: client_server.CMsgClientClanState,
    EMsg.ClientFriendsList: client_server_friends.CMsgClientFriendsList,
    EMsg.ClientRequestFriendData: client_server_friends.CMsgClientRequestFriendData,
    EMsg.ClientFriendMsg: client_server_friends.CMsgClientFriendMsg,
    EMsg.ClientChatInvite: client_server.CMsgClientChatInvite,
    EMsg.ClientFriendMsgIncoming: client_server_friends.CMsgClientFriendMsgIncoming,
    EMsg.ClientFriendMsgEchoToSender: client_server_friends.CMsgClientFriendMsgIncoming,
    EMsg.ClientChatGetFriendMessageHistory: client_server_2.CMsgClientChatGetFriendMessageHistory,
    EMsg.ClientChatGetFriendMessageHistoryResponse: client_server_2.CMsgClientChatGetFriendMessageHistoryResponse,
    EMsg.ClientFriendsGroupsList: client_server_friends.CMsgClientFriendsGroupsList,
    EMsg.AMClientCreateFriendsGroup: client_server_friends.CMsgClientCreateFriendsGroup,
    EMsg.AMClientCreateFriendsGroupResponse: client_server_friends.CMsgClientCreateFriendsGroupResponse,
    EMsg.AMClientDeleteFriendsGroup: client_server_friends.CMsgClientDeleteFriendsGroup,
    EMsg.AMClientDeleteFriendsGroupResponse: client_server_friends.CMsgClientDeleteFriendsGroupResponse,
    EMsg.AMClientRenameFriendsGroup: client_server_friends.CMsgClientManageFriendsGroup,
    EMsg.AMClientRenameFriendsGroupResponse: client_server_friends.CMsgClientManageFriendsGroupResponse,
    EMsg.AMClientAddFriendToGroup: client_server_friends.CMsgClientAddFriendToGroup,
    EMsg.AMClientAddFriendToGroupResponse: client_server_friends.CMsgClientAddFriendToGroupResponse,
    EMsg.AMClientRemoveFriendFromGroup: client_server_friends.CMsgClientRemoveFriendFromGroup,
    EMsg.AMClientRemoveFriendFromGroupResponse: client_server_friends.CMsgClientRemoveFriendFromGroupResponse,
    EMsg.ClientPlayerNicknameList: client_server_friends.CMsgClientPlayerNicknameList,
    EMsg.AMClientSetPlayerNickname: client_server_friends.CMsgClientSetPlayerNickname,
    EMsg.AMClientSetPlayerNicknameResponse: client_server_friends.CMsgClientSetPlayerNicknameResponse,
    EMsg.ClientRegisterKey: client_server_2.CMsgClientRegisterKey,
    EMsg.ClientPurchaseResponse: client_server_2.CMsgClientPurchaseResponse,
    EMsg.ClientRequestFreeLicense: client_server_2.CMsgClientRequestFreeLicense,
    EMsg.ClientRequestFreeLicenseResponse: client_server_2.CMsgClientRequestFreeLicenseResponse,
    EMsg.ClientGetNumberOfCurrentPlayersDP: client_server_2.CMsgDPGetNumberOfCurrentPlayers,
    EMsg.ClientGetNumberOfCurrentPlayersDPResponse: client_server_2.CMsgDPGetNumberOfCurrentPlayersResponse,
    EMsg.ClientGetAppOwnershipTicket: client_server.CMsgClientGetAppOwnershipTicket,
    EMsg.ClientGetAppOwnershipTicketResponse: client_server.CMsgClientGetAppOwnershipTicketResponse,
    EMsg.ClientGameConnectTokens: client_server.CMsgClientGameConnectTokens,
    EMsg.ClientAuthList: client_server.CMsgClientAuthList,
    EMsg.ClientAuthListAck: client_server.CMsgClientAuthListAck,
    EMsg.ClientTicketAuthComplete: client_server.CMsgClientTicketAuthComplete,
    EMsg.ClientRequestEncryptedAppTicket: client_server.CMsgClientRequestEncryptedAppTicket,
    EMsg.ClientRequestEncryptedAppTicketResponse: client_server.CMsgClientRequestEncryptedAppTicketResponse,
    EMsg.ClientCurrentUIMode: client_server_2.CMsgClientUIMode,
    EMsg.ClientVanityURLChangedNotification: client_server_2.CMsgClientVanityURLChangedNotification,
    EMsg.ClientAMGetPersonaNameHistory: client_server.CMsgClientAMGetPersonaNameHistory,
    EMsg.ClientAMGetPersonaNameHistoryResponse: client_server.CMsgClientAMGetPersonaNameHistoryResponse,
    EMsg.ClientUnlockStreaming: client_server_2.CMsgAMUnlockStreaming,
    EMsg.ClientUnlockStreamingResponse: client_server_2.CMsgAMUnlockStreamingResponse,
    EMsg.ClientGetDepotDecryptionKey: client_server_2.CMsgClientGetDepotDecryptionKey,
    EMsg.ClientGetDepotDecryptionKeyResponse: client_server_2.CMsgClientGetDepotDecryptionKeyResponse,
    EMsg.ClientGetCDNAuthToken: client_server_2.CMsgClientGetCDNAuthToken,
    EMsg.ClientGetCDNAuthTokenResponse: client_server_2.CMsgClientGetCDNAuthTokenResponse,
    EMsg.ClientCheckAppBetaPassword: client_server_2.CMsgClientCheckAppBetaPassword,
    EMsg.ClientCheckAppBetaPasswordResponse: client_server_2.CMsgClientCheckAppBetaPasswordResponse,
    EMsg.ClientKickPlayingSession: client_server_2.CMsgClientKickPlayingSession,
    EMsg.ClientConcurrentSessionsBase: client_server_2.CMsgClientPlayingSessionState,
    EMsg.ClientToGC: client_server_2.CMsgGCClient,
    EMsg.ClientFromGC: client_server_2.CMsgGCClient,
    EMsg.ClientRichPresenceUpload: client_server_2.CMsgClientRichPresenceUpload,
    EMsg.ClientGetEmoticonList: client_server_friends.CMsgClientGetEmoticonList,
    EMsg.ClientEmoticonList: client_server_friends.CMsgClientEmoticonList,
}
