# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test_messages.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ComplexProtoMessage(betterproto.Message):
    number32: int = betterproto.uint32_field(1)
    number64: int = betterproto.uint64_field(2)
    list_number32: List[int] = betterproto.uint32_field(3)
    list_number64: List[int] = betterproto.uint64_field(4)
    messages: List["ComplexProtoMessageInnerMessage"] = betterproto.message_field(5)
    buffers: List["ComplexProtoMessageInnerBuffer"] = betterproto.message_field(6)


@dataclass
class ComplexProtoMessageInnerMessage(betterproto.Message):
    text: str = betterproto.string_field(1)
    numbers: List[int] = betterproto.uint32_field(2)


@dataclass
class ComplexProtoMessageInnerBuffer(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
    flags: List["ComplexProtoMessageInnerBufferFlags"] = betterproto.message_field(2)


@dataclass
class ComplexProtoMessageInnerBufferFlags(betterproto.Message):
    flag: bool = betterproto.bool_field(1)
