# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_shared_enums.proto
# plugin: python-betterproto
from __future__ import annotations

from dataclasses import dataclass

import betterproto


class DOTAGameMode(betterproto.Enum):
    NONE = 0
    AP = 1
    CM = 2
    RD = 3
    SD = 4
    AR = 5
    INTRO = 6
    HW = 7
    REVERSE_CM = 8
    XMAS = 9
    TUTORIAL = 10
    MO = 11
    LP = 12
    POOL1 = 13
    FH = 14
    CUSTOM = 15
    CD = 16
    BD = 17
    ABILITY_DRAFT = 18
    EVENT = 19
    ARDM = 20
    MID1V1 = 21
    ALL_DRAFT = 22
    TURBO = 23
    MUTATION = 24
    COACHES_CHALLENGE = 25


class DOTAGameState(betterproto.Enum):
    INIT = 0
    WAIT_FOR_PLAYERS_TO_LOAD = 1
    HERO_SELECTION = 2
    STRATEGY_TIME = 3
    PRE_GAME = 4
    GAME_IN_PROGRESS = 5
    POST_GAME = 6
    DISCONNECT = 7
    TEAM_SHOWCASE = 8
    CUSTOM_GAME_SETUP = 9
    WAIT_FOR_MAP_TO_LOAD = 10
    SCENARIO_SETUP = 11
    PLAYER_DRAFT = 12
    LAST = 13


class DOTAGCTeam(betterproto.Enum):
    GOOD_GUYS = 0
    BAD_GUYS = 1
    BROADCASTER = 2
    SPECTATOR = 3
    PLAYER_POOL = 4
    NOTEAM = 5
    CUSTOM_1 = 6
    CUSTOM_2 = 7
    CUSTOM_3 = 8
    CUSTOM_4 = 9
    CUSTOM_5 = 10
    CUSTOM_6 = 11
    CUSTOM_7 = 12
    CUSTOM_8 = 13
    NEUTRALS = 14


class EEvent(betterproto.Enum):
    NONE = 0
    DIRETIDE = 1
    SPRING_FESTIVAL = 2
    FROSTIVUS_2013 = 3
    COMPENDIUM_2014 = 4
    NEXON_PC_BANG = 5
    PWRD_DAC_2015 = 6
    NEW_BLOOM_2015 = 7
    INTERNATIONAL_2015 = 8
    FALL_MAJOR_2015 = 9
    ORACLE_PA = 10
    NEW_BLOOM_2015_PREBEAST = 11
    FROSTIVUS = 12
    WINTER_MAJOR_2016 = 13
    INTERNATIONAL_2016 = 14
    FALL_MAJOR_2016 = 15
    WINTER_MAJOR_2017 = 16
    NEW_BLOOM_2017 = 17
    INTERNATIONAL_2017 = 18
    PLUS_SUBSCRIPTION = 19
    SINGLES_DAY_2017 = 20
    FROSTIVUS_2017 = 21
    INTERNATIONAL_2018 = 22
    FROSTIVUS_2018 = 23
    NEW_BLOOM_2019 = 24
    INTERNATIONAL_2019 = 25
    NEW_PLAYER_EXPERIENCE = 26
    FROSTIVUS_2019 = 27
    NEW_BLOOM_2020 = 28
    INTERNATIONAL_2020 = 29
    TEAM_FANDOM = 30
    DIRETIDE_2020 = 31
    SPRING_2021 = 32
    FALL_2021 = 33
    TEAM_FANDOM_FALL_2021 = 34
    TEAM_2021_2022_TOUR2 = 35
    INTERNATIONAL_2022 = 36
    TEAM_2021_2022_TOUR3 = 37
    TEAM_INTERNATIONAL_2022 = 38
    PERMANENT_GRANTS = 39
    MUERTA_RELEASE_SPRING2023 = 40
    TEAM_2023_TOUR1 = 41
    TEAM_2023_TOUR2 = 42
    TEAM_2023_TOUR3 = 43
    INTERNATIONAL_2023 = 45
    TENTH_ANNIVERSARY = 46
    FROSTIVUS_2023 = 48


class ERankType(betterproto.Enum):
    Invalid = 0
    Casual = 1
    Ranked = 2
    CasualLegacy = 3
    RankedLegacy = 4
    CasualGlicko = 5
    RankedGlicko = 6
    RankMax = 7
    BehaviorPrivate = 100
    BehaviorPublic = 101
    Max = 102


class DOTALeaverStatusT(betterproto.Enum):
    NONE = 0
    DISCONNECTED = 1
    DISCONNECTED_TOO_LONG = 2
    ABANDONED = 3
    AFK = 4
    NEVER_CONNECTED = 5
    NEVER_CONNECTED_TOO_LONG = 6
    FAILED_TO_READY_UP = 7
    DECLINED = 8


class DOTAConnectionStateT(betterproto.Enum):
    UNKNOWN = 0
    NOT_YET_CONNECTED = 1
    CONNECTED = 2
    DISCONNECTED = 3
    ABANDONED = 4
    LOADING = 5
    FAILED = 6


class FantasyRoles(betterproto.Enum):
    UNDEFINED = 0
    CORE = 1
    SUPPORT = 2
    OFFLANE = 3
    MID = 4


class FantasyScoring(betterproto.Enum):
    KILLS = 0
    DEATHS = 1
    CS = 2
    GPM = 3
    TOWER_KILLS = 4
    ROSHAN_KILLS = 5
    TEAMFIGHT_PARTICIPATION = 6
    WARDS_PLANTED = 7
    CAMPS_STACKED = 8
    RUNES_GRABBED = 9
    FIRST_BLOOD = 10
    STUNS = 11
    SMOKES_USED = 12
    NEUTRAL_TOKENS_FOUND = 13
    WATCHERS_TAKEN = 14
    LOTUSES_GAINED = 15
    TORMENTOR_KILLS = 16
    COURIER_KILLS = 17
    TYPES = 18
    INVALID = 19


class FantasyTeamSlots(betterproto.Enum):
    NONE = 0
    CORE = 1
    SUPPORT = 2
    ANY = 3
    BENCH = 4


class FantasySelectionMode(betterproto.Enum):
    INVALID = 0
    LOCKED = 1
    SHUFFLE = 2
    FREE_PICK = 3
    ENDED = 4
    PRE_SEASON = 5
    PRE_DRAFT = 6
    DRAFTING = 7
    REGULAR_SEASON = 8
    CARD_BASED = 9


class FantasyGemType(betterproto.Enum):
    RUBY = 0
    SAPPHIRE = 1
    EMERALD = 2


class DOTAChatChannelTypeT(betterproto.Enum):
    Regional = 0
    Custom = 1
    Party = 2
    Lobby = 3
    Team = 4
    Guild = 5
    Fantasy = 6
    Whisper = 7
    Console = 8
    Tab = 9
    Invalid = 10
    GameAll = 11
    GameAllies = 12
    GameSpectator = 13
    GameCoaching = 14
    Cafe = 15
    CustomGame = 16
    Private = 17
    PostGame = 18
    BattleCup = 19
    HLTVSpectator = 20
    GameEvents = 21
    Trivia = 22
    NewPlayer = 23
    PrivateCoaching = 24


class EChatSpecialPrivileges(betterproto.Enum):
    NONE = 0
    Moderator = 1
    SuperModerator = 2


class DOTACommTypeT(betterproto.Enum):
    NONE = 0
    PING = 1
    CHATWHEEL = 2
    TIP = 3
    TEXT = 4
    SHOWCASE = 5
    VOICE = 6
    ALLY_ABILITY = 7
    PAUSE = 8
    COACHING = 9
    NOCOOLDOWN = 10
    RANKEDMATCHMAKE = 11
    DROPS = 12
    NEWPLAYER_EXPERT = 13
    COACHED = 14
    MAPDRAWING = 15


class DOTACommLevelT(betterproto.Enum):
    NONE = 0
    COOLDOWN = 1
    PINGS = 2
    MAPDRAWING = 3
    CHAT = 4
    TIPPING = 5
    VOICE = 6
    ALLIED_ABILITY = 7


class DOTABehaviorLevelT(betterproto.Enum):
    NONE = 0
    RANKED_ALLOWED = 1
    PAUSING = 2
    DROPS = 3
    COACHING = 4


class EProfileCardSlotType(betterproto.Enum):
    Empty = 0
    Stat = 1
    Trophy = 2
    Item = 3
    Hero = 4
    Emoticon = 5
    Team = 6


class EMatchGroupServerStatus(betterproto.Enum):
    OK = 0
    LimitedAvailability = 1
    Offline = 2


class DOTACMPICK(betterproto.Enum):
    RANDOM = 0
    GOOD_GUYS = 1
    BAD_GUYS = 2


class DOTALowPriorityBanType(betterproto.Enum):
    ABANDON = 0
    REPORTS = 1
    SECONDARY_ABANDON = 2
    PRE_GAME_ROLE = 3


class DOTALobbyReadyState(betterproto.Enum):
    UNDECLARED = 0
    ACCEPTED = 1
    DECLINED = 2


class DOTAJoinLobbyResult(betterproto.Enum):
    SUCCESS = 0
    ALREADY_IN_GAME = 1
    INVALID_LOBBY = 2
    INCORRECT_PASSWORD = 3
    ACCESS_DENIED = 4
    GENERIC_ERROR = 5
    INCORRECT_VERSION = 6
    IN_TEAM_PARTY = 7
    NO_LOBBY_FOUND = 8
    LOBBY_FULL = 9
    CUSTOM_GAME_INCORRECT_VERSION = 10
    TIMEOUT = 11
    CUSTOM_GAME_COOLDOWN = 12
    BUSY = 13
    NO_PLAYTIME = 14


class DOTASelectionPriorityRules(betterproto.Enum):
    Manual = 0
    Automatic = 1


class DOTASelectionPriorityChoice(betterproto.Enum):
    Invalid = 0
    FirstPick = 1
    SecondPick = 2
    Radiant = 3
    Dire = 4


class DOTAMatchVote(betterproto.Enum):
    INVALID = 0
    POSITIVE = 1
    NEGATIVE = 2


class DOTALobbyVisibility(betterproto.Enum):
    Public = 0
    Friends = 1
    Unlisted = 2


class EDOTAPlayerMMRType(betterproto.Enum):
    Invalid = 0
    GeneralHidden = 1
    GeneralCompetitive = 3


class EDOTAMMRBoostType(betterproto.Enum):
    NONE = 0
    Leader = 1
    Follower = 2


class MatchType(betterproto.Enum):
    CASUAL = 0
    COOP_BOTS = 1
    COMPETITIVE = 4
    WEEKEND_TOURNEY = 5
    EVENT = 7
    COACHES_CHALLENGE = 12
    NEW_PLAYER_POOL = 14


class DOTABotDifficulty(betterproto.Enum):
    PASSIVE = 0
    EASY = 1
    MEDIUM = 2
    HARD = 3
    UNFAIR = 4
    INVALID = 5
    EXTRA1 = 6
    EXTRA2 = 7
    EXTRA3 = 8
    NPX = 9


class DOTABotMode(betterproto.Enum):
    NONE = 0
    LANING = 1
    ATTACK = 2
    ROAM = 3
    RETREAT = 4
    SECRET_SHOP = 5
    SIDE_SHOP = 6
    RUNE = 7
    PUSH_TOWER_TOP = 8
    PUSH_TOWER_MID = 9
    PUSH_TOWER_BOT = 10
    DEFEND_TOWER_TOP = 11
    DEFEND_TOWER_MID = 12
    DEFEND_TOWER_BOT = 13
    ASSEMBLE = 14
    ASSEMBLE_WITH_HUMANS = 15
    TEAM_ROAM = 16
    FARM = 17
    DEFEND_ALLY = 18
    EVASIVE_MANEUVERS = 19
    ROSHAN = 20
    ITEM = 21
    WARD = 22
    COMPANION = 23
    TUTORIAL_BOSS = 24
    MINION = 25
    OUTPOST = 26


class MatchLanguages(betterproto.Enum):
    INVALID = 0
    ENGLISH = 1
    RUSSIAN = 2
    CHINESE = 3
    KOREAN = 4
    SPANISH = 5
    PORTUGUESE = 6
    ENGLISH2 = 7


class ETourneyQueueDeadlineState(betterproto.Enum):
    Normal = 0
    Missed = 1
    ExpiredOK = 2
    SeekingBye = 3
    EligibleForRefund = 4
    NA = -1
    ExpiringSoon = 101


class EMatchOutcome(betterproto.Enum):
    Unknown = 0
    RadVictory = 2
    DireVictory = 3
    NeutralVictory = 4
    NoTeamWinner = 5
    Custom1Victory = 6
    Custom2Victory = 7
    Custom3Victory = 8
    Custom4Victory = 9
    Custom5Victory = 10
    Custom6Victory = 11
    Custom7Victory = 12
    Custom8Victory = 13
    NotScored_PoorNetworkConditions = 64
    NotScored_Leaver = 65
    NotScored_ServerCrash = 66
    NotScored_NeverStarted = 67
    NotScored_Canceled = 68
    NotScored_Suspicious = 69


class ELaneType(betterproto.Enum):
    UNKNOWN = 0
    SAFE = 1
    OFF = 2
    MID = 3
    JUNGLE = 4
    ROAM = 5


class EBadgeType(betterproto.Enum):
    Invalid = 0
    TI7_Midweek = 1
    TI7_Finals = 2
    TI7_AllEvent = 3
    TI8_Midweek = 4
    TI8_Finals = 5
    TI8_AllEvent = 6
    TI10 = 7
    TI11_PlayoffsDay1 = 8
    TI11_PlayoffsDay2 = 9
    TI11_PlayoffsDay3 = 10
    TI11_PlayoffsDay4 = 11
    TI11_FinalsWeekend = 12
    TI12_PlayoffsDay1 = 13
    TI12_PlayoffsDay2 = 14
    TI12_PlayoffsDay3 = 15
    TI12_FinalsWeekend = 16
    TI12_Special = 17


class ELeagueStatus(betterproto.Enum):
    UNSET = 0
    UNSUBMITTED = 1
    SUBMITTED = 2
    ACCEPTED = 3
    REJECTED = 4
    CONCLUDED = 5
    DELETED = 6


class ELeagueRegion(betterproto.Enum):
    UNSET = 0
    NA = 1
    SA = 2
    WEU = 3
    EEU = 4
    CHINA = 5
    SEA = 6


class ELeagueTier(betterproto.Enum):
    UNSET = 0
    AMATEUR = 1
    PROFESSIONAL = 2
    MINOR = 3
    MAJOR = 4
    INTERNATIONAL = 5
    DPC_QUALIFIER = 6
    DPC_LEAGUE_QUALIFIER = 7
    DPC_LEAGUE = 8
    DPC_LEAGUE_FINALS = 9


class ELeagueTierCategory(betterproto.Enum):
    AMATEUR = 1
    PROFESSIONAL = 2
    DPC = 3


class ELeagueDivision(betterproto.Enum):
    UNSET = 0
    I = 1
    II = 2


class ELeagueBroadcastProvider(betterproto.Enum):
    UNKNOWN = 0
    STEAM = 1
    TWITCH = 2
    YOUTUBE = 3
    OTHER = 100


class ELeaguePhase(betterproto.Enum):
    UNSET = 0
    REGIONAL_QUALIFIER = 1
    GROUP_STAGE = 2
    MAIN_EVENT = 3


class ELeagueAuditAction(betterproto.Enum):
    INVALID = 0
    LEAGUE_CREATE = 1
    LEAGUE_EDIT = 2
    LEAGUE_DELETE = 3
    LEAGUE_ADMIN_ADD = 4
    LEAGUE_ADMIN_REVOKE = 5
    LEAGUE_ADMIN_PROMOTE = 6
    LEAGUE_STREAM_ADD = 7
    LEAGUE_STREAM_REMOVE = 8
    LEAGUE_IMAGE_UPDATED = 9
    LEAGUE_MESSAGE_ADDED = 10
    LEAGUE_SUBMITTED = 11
    LEAGUE_SET_PRIZE_POOL = 12
    LEAGUE_ADD_PRIZE_POOL_ITEM = 13
    LEAGUE_REMOVE_PRIZE_POOL_ITEM = 14
    LEAGUE_MATCH_START = 15
    LEAGUE_MATCH_END = 16
    LEAGUE_ADD_INVITED_TEAM = 17
    LEAGUE_REMOVE_INVITED_TEAM = 18
    LEAGUE_STATUS_CHANGED = 19
    LEAGUE_STREAM_EDIT = 20
    LEAGUE_TEAM_SWAP = 21
    NODEGROUP_CREATE = 100
    NODEGROUP_DESTROY = 101
    NODEGROUP_ADD_TEAM = 102
    NODEGROUP_REMOVE_TEAM = 103
    NODEGROUP_SET_ADVANCING = 104
    NODEGROUP_EDIT = 105
    NODEGROUP_POPULATE = 106
    NODEGROUP_COMPLETED = 107
    NODEGROUP_SET_SECONDARY_ADVANCING = 108
    NODEGROUP_SET_TERTIARY_ADVANCING = 109
    NODE_CREATE = 200
    NODE_DESTROY = 201
    NODE_AUTOCREATE = 202
    NODE_SET_TEAM = 203
    NODE_SET_SERIES_ID = 204
    NODE_SET_ADVANCING = 205
    NODE_SET_TIME = 206
    NODE_MATCH_COMPLETED = 207
    NODE_COMPLETED = 208
    NODE_EDIT = 209


class DOTACombatLogTypes(betterproto.Enum):
    INVALID = -1
    DAMAGE = 0
    HEAL = 1
    MODIFIER_ADD = 2
    MODIFIER_REMOVE = 3
    DEATH = 4
    ABILITY = 5
    ITEM = 6
    LOCATION = 7
    GOLD = 8
    GAME_STATE = 9
    XP = 10
    PURCHASE = 11
    BUYBACK = 12
    ABILITY_TRIGGER = 13
    PLAYERSTATS = 14
    MULTIKILL = 15
    KILLSTREAK = 16
    TEAM_BUILDING_KILL = 17
    FIRST_BLOOD = 18
    MODIFIER_STACK_EVENT = 19
    NEUTRAL_CAMP_STACK = 20
    PICKUP_RUNE = 21
    REVEALED_INVISIBLE = 22
    HERO_SAVED = 23
    MANA_RESTORED = 24
    HERO_LEVELUP = 25
    BOTTLE_HEAL_ALLY = 26
    ENDGAME_STATS = 27
    INTERRUPT_CHANNEL = 28
    ALLIED_GOLD = 29
    AEGIS_TAKEN = 30
    MANA_DAMAGE = 31
    PHYSICAL_DAMAGE_PREVENTED = 32
    UNIT_SUMMONED = 33
    ATTACK_EVADE = 34
    TREE_CUT = 35
    SUCCESSFUL_SCAN = 36
    END_KILLSTREAK = 37
    BLOODSTONE_CHARGE = 38
    CRITICAL_DAMAGE = 39
    SPELL_ABSORB = 40
    UNIT_TELEPORTED = 41
    KILL_EATER_EVENT = 42
    NEUTRAL_ITEM_EARNED = 43


class EDPCFavoriteType(betterproto.Enum):
    ALL = 0
    PLAYER = 1
    TEAM = 2
    LEAGUE = 3


class EDPCPushNotification(betterproto.Enum):
    MATCH_STARTING = 1
    PLAYER_LEFT_TEAM = 10
    PLAYER_JOINED_TEAM = 11
    PLAYER_JOINED_TEAM_AS_COACH = 12
    PLAYER_LEFT_TEAM_AS_COACH = 13
    LEAGUE_RESULT = 20
    PREDICTION_MATCHES_AVAILABLE = 30
    PREDICTION_RESULT = 31
    FANTASY_PLAYER_CLEARED = 40
    FANTASY_DAILY_SUMMARY = 41
    FANTASY_FINAL_RESULTS = 42


class EEventActionScoreMode(betterproto.Enum):
    Add = 0
    Min = 1


class EPlayerChallengeHistoryType(betterproto.Enum):
    Invalid = 0
    KillEater = 1
    DotaPlusRelic = 2
    DotaPlusHeroPlayerChallenge = 3
    InGameEventChallenge = 4
    GuildContract = 5


class EOverwatchReportReason(betterproto.Enum):
    Unknown = 0
    Cheating = 1
    Feeding = 2
    Griefing = 3
    Suspicious = 4
    AbilityAbuse = 5


@dataclass
class CDOTAClientHardwareSpecs(betterproto.Message):
    logical_processors: int = betterproto.uint32_field(1)
    cpu_cycles_per_second: float = betterproto.fixed64_field(2)
    total_physical_memory: float = betterproto.fixed64_field(3)
    is_64_bit_os: bool = betterproto.bool_field(4)
    upload_measurement: int = betterproto.uint64_field(5)
    prefer_not_host: bool = betterproto.bool_field(6)
    crc: list[int] = betterproto.uint32_field(7)


@dataclass
class CDOTASaveGame(betterproto.Message):
    match_id: int = betterproto.uint64_field(5)
    save_time: int = betterproto.uint32_field(2)
    players: list[CDOTASaveGamePlayer] = betterproto.message_field(3)
    save_instances: list[CDOTASaveGameSaveInstance] = betterproto.message_field(4)


@dataclass
class CDOTASaveGamePlayer(betterproto.Message):
    team: DOTAGCTeam = betterproto.enum_field(1)
    name: str = betterproto.string_field(2)
    hero: str = betterproto.string_field(3)


@dataclass
class CDOTASaveGameSaveInstance(betterproto.Message):
    game_time: int = betterproto.uint32_field(2)
    team1_score: int = betterproto.uint32_field(3)
    team2_score: int = betterproto.uint32_field(4)
    player_positions: list[CDOTASaveGameSaveInstancePlayerPositions] = betterproto.message_field(5)
    save_id: int = betterproto.uint32_field(6)
    save_time: int = betterproto.uint32_field(7)


@dataclass
class CDOTASaveGameSaveInstancePlayerPositions(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)


@dataclass
class CMsgDOTACombatLogEntry(betterproto.Message):
    type: DOTACombatLogTypes = betterproto.enum_field(1)
    target_name: int = betterproto.uint32_field(2)
    target_source_name: int = betterproto.uint32_field(3)
    attacker_name: int = betterproto.uint32_field(4)
    damage_source_name: int = betterproto.uint32_field(5)
    inflictor_name: int = betterproto.uint32_field(6)
    is_attacker_illusion: bool = betterproto.bool_field(7)
    is_attacker_hero: bool = betterproto.bool_field(8)
    is_target_illusion: bool = betterproto.bool_field(9)
    is_target_hero: bool = betterproto.bool_field(10)
    is_visible_radiant: bool = betterproto.bool_field(11)
    is_visible_dire: bool = betterproto.bool_field(12)
    value: int = betterproto.uint32_field(13)
    health: int = betterproto.int32_field(14)
    timestamp: float = betterproto.float_field(15)
    stun_duration: float = betterproto.float_field(16)
    slow_duration: float = betterproto.float_field(17)
    is_ability_toggle_on: bool = betterproto.bool_field(18)
    is_ability_toggle_off: bool = betterproto.bool_field(19)
    ability_level: int = betterproto.uint32_field(20)
    location_x: float = betterproto.float_field(21)
    location_y: float = betterproto.float_field(22)
    gold_reason: int = betterproto.uint32_field(23)
    timestamp_raw: float = betterproto.float_field(24)
    modifier_duration: float = betterproto.float_field(25)
    xp_reason: int = betterproto.uint32_field(26)
    last_hits: int = betterproto.uint32_field(27)
    attacker_team: int = betterproto.uint32_field(28)
    target_team: int = betterproto.uint32_field(29)
    obs_wards_placed: int = betterproto.uint32_field(30)
    assist_player0: int = betterproto.uint32_field(31)
    assist_player1: int = betterproto.uint32_field(32)
    assist_player2: int = betterproto.uint32_field(33)
    assist_player3: int = betterproto.uint32_field(34)
    stack_count: int = betterproto.uint32_field(35)
    hidden_modifier: bool = betterproto.bool_field(36)
    is_target_building: bool = betterproto.bool_field(37)
    neutral_camp_type: int = betterproto.uint32_field(38)
    rune_type: int = betterproto.uint32_field(39)
    assist_players: list[int] = betterproto.int32_field(40)
    is_heal_save: bool = betterproto.bool_field(41)
    is_ultimate_ability: bool = betterproto.bool_field(42)
    attacker_hero_level: int = betterproto.uint32_field(43)
    target_hero_level: int = betterproto.uint32_field(44)
    xpm: int = betterproto.uint32_field(45)
    gpm: int = betterproto.uint32_field(46)
    event_location: int = betterproto.uint32_field(47)
    target_is_self: bool = betterproto.bool_field(48)
    damage_type: int = betterproto.uint32_field(49)
    invisibility_modifier: bool = betterproto.bool_field(50)
    damage_category: int = betterproto.uint32_field(51)
    networth: int = betterproto.uint32_field(52)
    building_type: int = betterproto.uint32_field(53)
    modifier_elapsed_duration: float = betterproto.float_field(54)
    silence_modifier: bool = betterproto.bool_field(55)
    heal_from_lifesteal: bool = betterproto.bool_field(56)
    modifier_purged: bool = betterproto.bool_field(57)
    spell_evaded: bool = betterproto.bool_field(58)
    motion_controller_modifier: bool = betterproto.bool_field(59)
    long_range_kill: bool = betterproto.bool_field(60)
    modifier_purge_ability: int = betterproto.uint32_field(61)
    modifier_purge_npc: int = betterproto.uint32_field(62)
    root_modifier: bool = betterproto.bool_field(63)
    total_unit_death_count: int = betterproto.uint32_field(64)
    aura_modifier: bool = betterproto.bool_field(65)
    armor_debuff_modifier: bool = betterproto.bool_field(66)
    no_physical_damage_modifier: bool = betterproto.bool_field(67)
    modifier_ability: int = betterproto.uint32_field(68)
    modifier_hidden: bool = betterproto.bool_field(69)
    inflictor_is_stolen_ability: bool = betterproto.bool_field(70)
    kill_eater_event: int = betterproto.uint32_field(71)
    unit_status_label: int = betterproto.uint32_field(72)
    spell_generated_attack: bool = betterproto.bool_field(73)
    at_night_time: bool = betterproto.bool_field(74)
    attacker_has_scepter: bool = betterproto.bool_field(75)
    neutral_camp_team: int = betterproto.uint32_field(76)
    regenerated_health: float = betterproto.float_field(77)
    will_reincarnate: bool = betterproto.bool_field(78)
    uses_charges: bool = betterproto.bool_field(79)


@dataclass
class CMsgPendingEventAward(betterproto.Message):
    event_id: EEvent = betterproto.enum_field(1)
    action_id: int = betterproto.uint32_field(2)
    num_to_grant: int = betterproto.uint32_field(3)
    score_mode: EEventActionScoreMode = betterproto.enum_field(4)
    audit_action: int = betterproto.uint32_field(5)
    audit_data: int = betterproto.uint64_field(6)
