# -*- coding: utf-8 -*-

"""
Copyright (c) 2015 Rossen Georgiev <rossen@rgp.io>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Taken from https://github.com/ValvePython/steam/blob/master/steam/enums/common.py
"""

import enum


class URL:
    API = 'https://api.steampowered.com'
    COMMUNITY = 'https://steamcommunity.com'
    STORE = 'https://store.steampowered.com'


class EResult(enum.IntEnum):
    Invalid = 0
    OK = 1  #: success
    Fail = 2  #: generic failure
    NoConnection = 3  #: no/failed network connection
    InvalidPassword = 5  #: password/ticket is invalid
    LoggedInElsewhere = 6  #: same user logged in elsewhere
    InvalidProtocolVer = 7  #: protocol version is incorrect
    InvalidParam = 8  #: a parameter is incorrect
    FileNotFound = 9  #: file was not found
    Busy = 10  #: called method busy - action not taken
    InvalidState = 11  #: called object was in an invalid state
    InvalidName = 12  #: name is invalid
    InvalidEmail = 13  #: email is invalid
    DuplicateName = 14  #: name is not unique
    AccessDenied = 15  #: access is denied
    Timeout = 16  #: operation timed out
    Banned = 17  #: VAC2 banned
    AccountNotFound = 18  #: account not found
    InvalidSteamID = 19  #: steamID is invalid
    ServiceUnavailable = 20  #: The requested service is currently unavailable
    NotLoggedOn = 21  #: The user is not logged on
    Pending = 22  #: Request is pending (may be in process, or waiting on third party)
    EncryptionFailure = 23  #: Encryption or Decryption failed
    InsufficientPrivilege = 24  #: Insufficient privilege
    LimitExceeded = 25  #: Too much of a good thing
    Revoked = 26  #: Access has been revoked (used for revoked guest passes)
    Expired = 27  #: License/Guest pass the user is trying to access is expired
    AlreadyRedeemed = 28  #: Guest pass has already been redeemed by account, cannot be acked again
    DuplicateRequest = 29  #: The request is a duplicate and the action has already occurred in the past, ignored this time
    AlreadyOwned = 30  #: All the games in this guest pass redemption request are already owned by the user
    IPNotFound = 31  #: IP address not found
    PersistFailed = 32  #: failed to write change to the data store
    LockingFailed = 33  #: failed to acquire access lock for this operation
    LogonSessionReplaced = 34
    ConnectFailed = 35
    HandshakeFailed = 36
    IOFailure = 37
    RemoteDisconnect = 38
    ShoppingCartNotFound = 39  #: failed to find the shopping cart requested
    Blocked = 40  #: a user didn't allow it
    Ignored = 41  #: target is ignoring sender
    NoMatch = 42  #: nothing matching the request found
    AccountDisabled = 43
    ServiceReadOnly = 44  #: this service is not accepting content changes right now
    AccountNotFeatured = 45  #: account doesn't have value, so this feature isn't available
    AdministratorOK = 46  #: allowed to take this action, but only because requester is admin
    ContentVersion = 47  #: A Version mismatch in content transmitted within the Steam protocol.
    TryAnotherCM = 48  #: The current CM can't service the user making a request, user should try another.
    PasswordRequiredToKickSession = 49  #: You are already logged in elsewhere, this cached credential login has failed.
    AlreadyLoggedInElsewhere = 50  #: You are already logged in elsewhere, you must wait
    Suspended = 51  #: Long running operation (content download) suspended/paused
    Cancelled = 52  #: Operation canceled (typically by user: content download)
    DataCorruption = 53  #: Operation canceled because data is ill formed or unrecoverable
    DiskFull = 54  #: Operation canceled - not enough disk space.
    RemoteCallFailed = 55  #: an remote call or IPC call failed
    PasswordUnset = 56  #: Password could not be verified as it's unset server side
    ExternalAccountUnlinked = 57  #: External account (PSN, Facebook...) is not linked to a Steam account
    PSNTicketInvalid = 58  #: PSN ticket was invalid
    ExternalAccountAlreadyLinked = 59  #: External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first
    RemoteFileConflict = 60  #: The sync cannot resume due to a conflict between the local and remote files
    IllegalPassword = 61  #: The requested new password is not legal
    SameAsPreviousValue = 62  #: new value is the same as the old one ( secret question and answer )
    AccountLogonDenied = 63  #: account login denied due to 2nd factor authentication failure
    CannotUseOldPassword = 64  #: The requested new password is not legal
    InvalidLoginAuthCode = 65  #: account login denied due to auth code invalid
    AccountLogonDeniedNoMail = 66  #: account login denied due to 2nd factor auth failure - and no mail has been sent
    HardwareNotCapableOfIPT = 67
    IPTInitError = 68
    ParentalControlRestricted = 69  #: operation failed due to parental control restrictions for current user
    FacebookQueryError = 70  #: Facebook query returned an error
    ExpiredLoginAuthCode = 71  #: account login denied due to auth code expired
    IPLoginRestrictionFailed = 72
    AccountLockedDown = 73
    AccountLogonDeniedVerifiedEmailRequired = 74
    NoMatchingURL = 75
    BadResponse = 76  #: parse failure, missing field, etc.
    RequirePasswordReEntry = 77  #: The user cannot complete the action until they re-enter their password
    ValueOutOfRange = 78  #: the value entered is outside the acceptable range
    UnexpectedError = 79  #: something happened that we didn't expect to ever happen
    Disabled = 80  #: The requested service has been configured to be unavailable
    InvalidCEGSubmission = 81  #: The set of files submitted to the CEG server are not valid !
    RestrictedDevice = 82  #: The device being used is not allowed to perform this action
    RegionLocked = 83  #: The action could not be complete because it is region restricted
    RateLimitExceeded = 84  #: Temporary rate limit exceeded, try again later, different from k_EResultLimitExceeded which may be permanent
    AccountLoginDeniedNeedTwoFactor = 85  #: Need two-factor code to login
    ItemDeleted = 86  #: The thing we're trying to access has been deleted
    AccountLoginDeniedThrottle = 87  #: login attempt failed, try to throttle response to possible attacker
    TwoFactorCodeMismatch = 88  #: two factor code mismatch
    TwoFactorActivationCodeMismatch = 89  #: activation code for two-factor didn't match
    AccountAssociatedToMultiplePartners = 90  #: account has been associated with multiple partners
    NotModified = 91  #: data not modified
    NoMobileDevice = 92  #: the account does not have a mobile device associated with it
    TimeNotSynced = 93  #: the time presented is out of range or tolerance
    SMSCodeFailed = 94  #: SMS code failure (no match, none pending, etc.)
    AccountLimitExceeded = 95  #: Too many accounts access this resource
    AccountActivityLimitExceeded = 96  #: Too many changes to this account
    PhoneActivityLimitExceeded = 97  #: Too many changes to this phone
    RefundToWallet = 98  #: Cannot refund to payment method, must use wallet
    EmailSendFailure = 99  #: Cannot send an email
    NotSettled = 100  #: Can't perform operation till payment has settled
    NeedCaptcha = 101  #: Needs to provide a valid captcha
    GSLTDenied = 102  #: a game server login token owned by this token's owner has been banned
    GSOwnerDenied = 103  #: game server owner is denied for other reason (account lock, community ban, vac ban, missing phone)
    InvalidItemType = 104  #: the type of thing we were requested to act on is invalid
    IPBanned = 105  #: the ip address has been banned from taking this action
    GSLTExpired = 106  #: this token has expired from disuse; can be reset for use
    InsufficientFunds = 107  #: user doesn't have enough wallet funds to complete the action
    TooManyPending = 108  #: There are too many of this thing pending already
    NoSiteLicensesFound = 109  #: No site licenses found
    WGNetworkSendExceeded = 110  #: the WG couldn't send a response because we exceeded max network send size


class EUniverse(enum.IntEnum):
    Invalid = 0
    Public = 1
    Beta = 2
    Internal = 3
    Dev = 4
    Max = 6


class EType(enum.IntEnum):
    Invalid = 0
    Individual = 1  #: single user account
    Multiseat = 2  #: multiseat (e.g. cybercafe) account
    GameServer = 3  #: game server account
    AnonGameServer = 4  #: anonymous game server account
    Pending = 5  #: pending
    ContentServer = 6  #: content server
    Clan = 7
    Chat = 8
    ConsoleUser = 9  #: Fake SteamID for local PSN account on PS3 or Live account on 360, etc.
    AnonUser = 10
    Max = 11


class EInstanceFlag(enum.IntEnum):
    MMSLobby = 0x20000
    Lobby = 0x40000
    Clan = 0x80000


class EVanityUrlType(enum.IntEnum):
    Individual = 1
    Group = 2
    GameGroup = 3


class EServerType(enum.IntEnum):
    Invalid = -1
    First = 0
    GM = 1
    AM = 3
    BS = 4
    VS = 5
    ATS = 6
    CM = 7
    FBS = 8
    BoxMonitor = 9
    SS = 10
    DRMS = 11
    HubOBSOLETE = 12
    Console = 13
    PICS = 14
    Client = 15
    BootstrapOBSOLETE = 16
    DP = 17
    WG = 18
    SM = 19
    SLC = 20
    UFS = 21
    Util = 23
    DSS = 24
    Community = 24
    P2PRelayOBSOLETE = 25
    AppInformation = 26
    Spare = 27
    FTS = 28
    PS = 30
    IS = 31
    CCS = 32
    DFS = 33
    LBS = 34
    MDS = 35
    CS = 36
    GC = 37
    NS = 38
    OGS = 39
    WebAPI = 40
    UDS = 41
    MMS = 42
    GMS = 43
    KGS = 44
    UCM = 45
    RM = 46
    FS = 47
    Econ = 48
    Backpack = 49
    UGS = 50
    StoreFeature = 51
    MoneyStats = 52
    CRE = 53
    UMQ = 54
    Workshop = 55
    BRP = 56
    GCH = 57
    MPAS = 58
    Trade = 59
    Secrets = 60
    Logsink = 61
    Market = 62
    Quest = 63
    WDS = 64
    ACS = 65
    PNP = 66
    TaxForm = 67
    ExternalMonitor = 68
    Parental = 69
    PartnerUpload = 70
    Partner = 71
    ES = 72
    DepotWebContent = 73
    ExternalConfig = 74
    GameNotifications = 75
    MarketRepl = 76
    MarketSearch = 77
    Localization = 78
    Steam2Emulator = 79
    PublicTest = 80
    SolrMgr = 81
    BroadcastRelay = 82
    BroadcastDirectory = 83
    VideoManager = 84
    TradeOffer = 85
    BroadcastChat = 86
    Phone = 87
    AccountScore = 88
    Support = 89
    LogRequest = 90
    LogWorker = 91
    EmailDelivery = 92
    InventoryManagement = 93
    Auth = 94
    StoreCatalog = 95
    HLTVRelay = 96

    Max = 97


class EOSType(enum.IntEnum):
    Unknown = -1

    IOSUnknown = -600

    AndroidUnknown = -500

    UMQ = -400

    PS3 = -300

    MacOSUnknown = -102
    MacOS104 = -101
    MacOS105 = -100
    MacOS1058 = -99
    MacOS106 = -95
    MacOS1063 = -94
    MacOS1064_slgu = -93
    MacOS1067 = -92
    MacOS107 = -90
    MacOS108 = -89
    MacOS109 = -88
    MacOS1010 = -87
    MacOS1011 = -86
    MacOS1012 = -85
    MacOSMax = -1

    LinuxUnknown = -203
    Linux22 = -202
    Linux24 = -201
    Linux26 = -200
    Linux32 = -199
    Linux35 = -198
    Linux36 = -197
    Linux310 = -196
    LinuxMax = -103

    WinUnknown = 0
    Win311 = 1
    Win95 = 2
    Win98 = 3
    WinME = 4
    WinNT = 5
    Win2000 = 6
    WinXP = 7
    Win2003 = 8
    WinVista = 9
    Windows7 = 10
    Win2008 = 11
    Win2012 = 12
    Windows8 = 13
    Windows81 = 14
    Win2012R2 = 15
    Windows10 = 16

    WinMAX = 15

    Max = 26


class EFriendRelationship(enum.IntEnum):
    NONE = 0
    Blocked = 1
    RequestRecipient = 2
    Friend = 3
    RequestInitiator = 4
    Ignored = 5
    IgnoredFriend = 6
    SuggestedFriend = 7
    Max = 8


class EAccountFlags(enum.IntEnum):
    NormalUser = 0
    PersonaNameSet = 1
    Unbannable = 2
    PasswordSet = 4
    Support = 8
    Admin = 16
    Supervisor = 32
    AppEditor = 64
    HWIDSet = 128
    PersonalQASet = 256
    VacBeta = 512
    Debug = 1024
    Disabled = 2048
    LimitedUser = 4096
    LimitedUserForce = 8192
    EmailValidated = 16384
    MarketingTreatment = 32768
    OGGInviteOptOut = 65536
    ForcePasswordChange = 131072
    ForceEmailVerification = 262144
    LogonExtraSecurity = 524288
    LogonExtraSecurityDisabled = 1048576
    Steam2MigrationComplete = 2097152
    NeedLogs = 4194304
    Lockdown = 8388608
    MasterAppEditor = 16777216
    BannedFromWebAPI = 33554432
    ClansOnlyFromFriends = 67108864
    GlobalModerator = 134217728
    ParentalSettings = 268435456
    ThirdPartySupport = 536870912
    NeedsSSANextSteamLogon = 1073741824


class EFriendFlags(enum.IntEnum):
    NONE = 0
    Blocked = 1
    FriendshipRequested = 2
    Immediate = 4
    ClanMember = 8
    OnGameServer = 16
    RequestingFriendship = 128
    RequestingInfo = 256
    Ignored = 512
    IgnoredFriend = 1024
    Suggested = 2048
    ChatMember = 4096
    FlagAll = 65535


class EPersonaState(enum.IntEnum):
    Offline = 0
    Online = 1
    Busy = 2
    Away = 3
    Snooze = 4
    LookingToTrade = 5
    LookingToPlay = 6
    Max = 7


class EPersonaStateFlag(enum.IntEnum):
    HasRichPresence = 1
    InJoinableGame = 2
    HasGoldenProfile = 4
    ClientTypeWeb = 256
    ClientTypeMobile = 512
    ClientTypeTenfoot = 1024
    ClientTypeVR = 2048
    LaunchTypeGamepad = 4096


class EClientPersonaStateFlag(enum.IntEnum):
    Status = 1
    PlayerName = 2
    QueryPort = 4
    SourceID = 8
    Presence = 16
    LastSeen = 64
    ClanInfo = 128
    GameExtraInfo = 256
    GameDataBlob = 512
    ClanTag = 1024
    Facebook = 2048


class EChatEntryType(enum.IntEnum):
    Invalid = 0
    ChatMsg = 1  #: Normal text message from another user
    Typing = 2  #: Another user is typing (not used in multi-user chat)
    InviteGame = 3  #: Invite from other user into that users current game
    Emote = 4  #: text emote message (deprecated, should be treated as ChatMsg)
    LobbyGameStart = 5  #: lobby game is starting (dead - listen for LobbyGameCreated_t callback instead)
    LeftConversation = 6  #: user has left the conversation ( closed chat window )
    Entered = 7  #: user has entered the conversation (used in multi-user chat and group chat)
    WasKicked = 8  #: user was kicked (data: 64-bit steamid of actor performing the kick)
    WasBanned = 9  #: user was banned (data: 64-bit steamid of actor performing the ban)
    Disconnected = 10  #: user disconnected
    HistoricalChat = 11  #: a chat message from user's chat history or offline message
    Reserved1 = 12  #: No longer used
    Reserved2 = 13  #: No longer used
    LinkBlocked = 14  #: a link was removed by the chat filter.


class EChatRoomEnterResponse(enum.IntEnum):
    Success = 1  #: Success
    DoesntExist = 2  #: Chat doesn't exist (probably closed)
    NotAllowed = 3  #: General Denied - You don't have the permissions needed to join the chat
    Full = 4  #: Chat room has reached its maximum size
    Error = 5  #: Unexpected Error
    Banned = 6  #: You are banned from this chat room and may not join
    Limited = 7  #: Joining this chat is not allowed because you are a limited user (no value on account)
    ClanDisabled = 8  #: Attempt to join a clan chat when the clan is locked or disabled
    CommunityBan = 9  #: Attempt to join a chat when the user has a community lock on their account
    MemberBlockedYou = 10  #: Join failed - some member in the chat has blocked you from joining
    YouBlockedMember = 11  #: Join failed - you have blocked some member already in the chat
    NoRankingDataLobby = 12  #: No longer used
    NoRankingDataUser = 13  #: No longer used
    RankOutOfRange = 14  #: No longer used
    RatelimitExceeded = 15  #: Join failed - to many join attempts in a very short period of time


class ECurrencyCode(enum.IntEnum):
    Invalid = 0
    USD = 1
    GBP = 2
    EUR = 3
    CHF = 4
    RUB = 5
    PLN = 6
    BRL = 7
    JPY = 8
    NOK = 9
    IDR = 10
    MYR = 11
    PHP = 12
    SGD = 13
    THB = 14
    VND = 15
    KRW = 16
    TRY = 17
    UAH = 18
    MXN = 19
    CAD = 20
    AUD = 21
    NZD = 22
    CNY = 23
    INR = 24
    CLP = 25
    PEN = 26
    COP = 27
    ZAR = 28
    HKD = 29
    TWD = 30
    SAR = 31
    AED = 32
    SEK = 33
    ARS = 34
    ILS = 35
    BYN = 36
    KZT = 37
    KWD = 38
    QAR = 39
    CRC = 40
    UYU = 41
    Max = 42


class ETradeOfferState(enum.IntEnum):
    Invalid = 1
    Active = 2
    Accepted = 3
    Countered = 4
    Expired = 5
    Canceled = 6
    Declined = 7
    InvalidItems = 8
    ConfirmationNeed = 9
    CanceledBySecondaryFactor = 10
    StateInEscrow = 11


class ETypeChar(enum.IntEnum):
    I = EType.Invalid
    U = EType.Individual
    M = EType.Multiseat
    G = EType.GameServer
    A = EType.AnonGameServer
    P = EType.Pending
    C = EType.ContentServer
    g = EType.Clan
    T = EType.Chat
    L = EType.Chat  # lobby chat, 'c' for clan chat
    c = EType.Chat  # clan chat
    a = EType.AnonUser

    def __str__(self):
        return self.name


class EMsg(enum.IntEnum):
    Invalid = 0
    Multi = 1
    ProtobufWrapped = 2

    BaseGeneral = 100
    GenericReply = 100
    DestJobFailed = 113
    Alert = 115
    SCIDRequest = 120
    SCIDResponse = 121
    JobHeartbeat = 123
    HubConnect = 124
    Subscribe = 126
    AMCreateAccountResponse = 129
    WGRequest = 130
    WGResponse = 131
    KeepAlive = 132
    WebAPIJobRequest = 133
    WebAPIJobResponse = 134
    ClientSessionStart = 135
    ClientSessionEnd = 136
    ClientSessionUpdate = 137
    Ping = 139
    PingResponse = 140
    Stats = 141
    RequestFullStatsBlock = 142
    LoadDBOCacheItem = 143
    LoadDBOCacheItemResponse = 144
    InvalidateDBOCacheItems = 145
    ServiceMethod = 146
    ServiceMethodResponse = 147
    ClientPackageVersions = 148
    TimestampRequest = 149
    TimestampResponse = 150
    ServiceMethodCallFromClient = 151
    ServiceMethodSendToClient = 152

    BaseShell = 200
    AssignSysID = 200
    Exit = 201
    DirRequest = 202
    DirResponse = 203
    ZipRequest = 204
    ZipResponse = 205
    UpdateRecordResponse = 215
    UpdateCreditCardRequest = 221
    UpdateUserBanResponse = 225
    PrepareToExit = 226
    ContentDescriptionUpdate = 227
    TestResetServer = 228
    UniverseChanged = 229
    ShellConfigInfoUpdate = 230
    RequestWindowsEventLogEntries = 233
    ProvideWindowsEventLogEntries = 234
    ShellSearchLogs = 235
    ShellSearchLogsResponse = 236
    ShellCheckWindowsUpdates = 237
    ShellCheckWindowsUpdatesResponse = 238

    BaseGM = 300
    Heartbeat = 300
    ShellFailed = 301
    ExitShells = 307
    ExitShell = 308
    GracefulExitShell = 309
    NotifyWatchdog = 314
    LicenseProcessingComplete = 316
    SetTestFlag = 317
    QueuedEmailsComplete = 318
    GMReportPHPError = 319
    GMDRMSync = 320
    PhysicalBoxInventory = 321
    UpdateConfigFile = 322
    TestInitDB = 323
    GMWriteConfigToSQL = 324
    GMLoadActivationCodes = 325
    GMQueueForFBS = 326
    GMSchemaConversionResults = 327
    GMWriteShellFailureToSQL = 329
    GMWriteStatsToSOS = 330
    GMGetServiceMethodRouting = 331
    GMGetServiceMethodRoutingResponse = 332
    GMConvertUserWallets = 333

    BaseAIS = 400
    AISRequestContentDescription = 402
    AISUpdateAppInfo = 403
    AISUpdatePackageCosts = 404
    AISGetPackageChangeNumber = 405
    AISGetPackageChangeNumberResponse = 406
    AISUpdatePackageCostsResponse = 408
    AISCreateMarketingMessage = 409
    AISCreateMarketingMessageResponse = 410
    AISGetMarketingMessage = 411
    AISGetMarketingMessageResponse = 412
    AISUpdateMarketingMessage = 413
    AISUpdateMarketingMessageResponse = 414
    AISRequestMarketingMessageUpdate = 415
    AISDeleteMarketingMessage = 416
    AIGetAppGCFlags = 423
    AIGetAppGCFlagsResponse = 424
    AIGetAppList = 425
    AIGetAppListResponse = 426
    AISGetCouponDefinition = 429
    AISGetCouponDefinitionResponse = 430
    AISUpdateSlaveContentDescription = 431
    AISUpdateSlaveContentDescriptionResponse = 432
    AISTestEnableGC = 433

    BaseAM = 500
    AMUpdateUserBanRequest = 504
    AMAddLicense = 505
    AMSendSystemIMToUser = 508
    AMExtendLicense = 509
    AMAddMinutesToLicense = 510
    AMCancelLicense = 511
    AMInitPurchase = 512
    AMPurchaseResponse = 513
    AMGetFinalPrice = 514
    AMGetFinalPriceResponse = 515
    AMGetLegacyGameKey = 516
    AMGetLegacyGameKeyResponse = 517
    AMFindHungTransactions = 518
    AMSetAccountTrustedRequest = 519
    AMCompletePurchase = 521
    AMCancelPurchase = 522
    AMNewChallenge = 523
    AMLoadOEMTickets = 524
    AMFixPendingPurchase = 525
    AMFixPendingPurchaseResponse = 526
    AMIsUserBanned = 527
    AMRegisterKey = 528
    AMLoadActivationCodes = 529
    AMLoadActivationCodesResponse = 530
    AMLookupKeyResponse = 531
    AMLookupKey = 532
    AMChatCleanup = 533
    AMClanCleanup = 534
    AMFixPendingRefund = 535
    AMReverseChargeback = 536
    AMReverseChargebackResponse = 537
    AMClanCleanupList = 538
    AMGetLicenses = 539
    AMGetLicensesResponse = 540
    AllowUserToPlayQuery = 550
    AllowUserToPlayResponse = 551
    AMVerfiyUser = 552
    AMClientNotPlaying = 553
    ClientRequestFriendship = 554
    AMRelayPublishStatus = 555
    AMInitPurchaseResponse = 560
    AMRevokePurchaseResponse = 561
    AMRefreshGuestPasses = 563
    AMInviteUserToClan = 564
    AMAcknowledgeClanInvite = 565
    AMGrantGuestPasses = 566
    AMClanDataUpdated = 567
    AMReloadAccount = 568
    AMClientChatMsgRelay = 569
    AMChatMulti = 570
    AMClientChatInviteRelay = 571
    AMChatInvite = 572
    AMClientJoinChatRelay = 573
    AMClientChatMemberInfoRelay = 574
    AMPublishChatMemberInfo = 575
    AMClientAcceptFriendInvite = 576
    AMChatEnter = 577
    AMClientPublishRemovalFromSource = 578
    AMChatActionResult = 579
    AMFindAccounts = 580
    AMFindAccountsResponse = 581
    AMRequestAccountData = 582
    AMRequestAccountDataResponse = 583
    AMSetAccountFlags = 584
    AMCreateClan = 586
    AMCreateClanResponse = 587
    AMGetClanDetails = 588
    AMGetClanDetailsResponse = 589
    AMSetPersonaName = 590
    AMSetAvatar = 591
    AMAuthenticateUser = 592
    AMAuthenticateUserResponse = 593
    AMP2PIntroducerMessage = 596
    ClientChatAction = 597
    AMClientChatActionRelay = 598

    BaseVS = 600
    ReqChallenge = 600
    VACResponse = 601
    ReqChallengeTest = 602
    VSMarkCheat = 604
    VSAddCheat = 605
    VSPurgeCodeModDB = 606
    VSGetChallengeResults = 607
    VSChallengeResultText = 608
    VSReportLingerer = 609
    VSRequestManagedChallenge = 610
    VSLoadDBFinished = 611

    BaseDRMS = 625
    DRMBuildBlobRequest = 628
    DRMBuildBlobResponse = 629
    DRMResolveGuidRequest = 630
    DRMResolveGuidResponse = 631
    DRMVariabilityReport = 633
    DRMVariabilityReportResponse = 634
    DRMStabilityReport = 635
    DRMStabilityReportResponse = 636
    DRMDetailsReportRequest = 637
    DRMDetailsReportResponse = 638
    DRMProcessFile = 639
    DRMAdminUpdate = 640
    DRMAdminUpdateResponse = 641
    DRMSync = 642
    DRMSyncResponse = 643
    DRMProcessFileResponse = 644
    DRMEmptyGuidCache = 645
    DRMEmptyGuidCacheResponse = 646

    BaseCS = 650

    BaseClient = 700
    ClientHeartBeat = 703
    ClientVACResponse = 704
    ClientLogOff = 706
    ClientNoUDPConnectivity = 707
    ClientInformOfCreateAccount = 708
    ClientAckVACBan = 709
    ClientConnectionStats = 710
    ClientPingResponse = 712
    ClientRemoveFriend = 714
    ClientGamesPlayedNoDataBlob = 715
    ClientChangeStatus = 716
    ClientVacStatusResponse = 717
    ClientFriendMsg = 718
    ClientSystemIM = 726
    ClientSystemIMAck = 727
    ClientGetLicenses = 728
    ClientGetLegacyGameKey = 730
    ClientAckVACBan2 = 732
    ClientGetPurchaseReceipts = 736
    ClientAckGuestPass = 740
    ClientRedeemGuestPass = 741
    ClientGamesPlayed = 742
    ClientRegisterKey = 743
    ClientInviteUserToClan = 744
    ClientAcknowledgeClanInvite = 745
    ClientPurchaseWithMachineID = 746
    ClientAppUsageEvent = 747
    ClientLogOnResponse = 751
    ClientVACChallenge = 753
    ClientSetHeartbeatRate = 755
    ClientLoggedOff = 757
    GSApprove = 758
    GSDeny = 759
    GSKick = 760
    ClientCreateAcctResponse = 761
    ClientPurchaseResponse = 763
    ClientPing = 764
    ClientNOP = 765
    ClientPersonaState = 766
    ClientFriendsList = 767
    ClientAccountInfo = 768
    ClientVacStatusQuery = 770
    ClientNewsUpdate = 771
    ClientGameConnectDeny = 773
    GSStatusReply = 774
    ClientGameConnectTokens = 779
    ClientLicenseList = 780
    ClientVACBanStatus = 782
    ClientCMList = 783
    ClientEncryptPct = 784
    ClientGetLegacyGameKeyResponse = 785
    ClientAddFriend = 791
    ClientAddFriendResponse = 792
    ClientAckGuestPassResponse = 796
    ClientRedeemGuestPassResponse = 797
    ClientUpdateGuestPassesList = 798
    ClientChatMsg = 799
    ClientChatInvite = 800
    ClientJoinChat = 801
    ClientChatMemberInfo = 802
    ClientPasswordChangeResponse = 805
    ClientChatEnter = 807
    ClientFriendRemovedFromSource = 808
    ClientCreateChat = 809
    ClientCreateChatResponse = 810
    ClientP2PIntroducerMessage = 813
    ClientChatActionResult = 814
    ClientRequestFriendData = 815
    ClientGetUserStats = 818
    ClientGetUserStatsResponse = 819
    ClientStoreUserStats = 820
    ClientStoreUserStatsResponse = 821
    ClientClanState = 822
    ClientServiceModule = 830
    ClientServiceCall = 831
    ClientServiceCallResponse = 832
    ClientPackageInfoRequest = 833
    ClientPackageInfoResponse = 834
    ClientNatTraversalStatEvent = 839
    ClientAppInfoRequest = 840
    ClientAppInfoResponse = 841
    ClientSteamUsageEvent = 842
    ClientCheckPassword = 845
    ClientResetPassword = 846
    ClientCheckPasswordResponse = 848
    ClientResetPasswordResponse = 849
    ClientSessionToken = 850
    ClientDRMProblemReport = 851
    ClientSetIgnoreFriend = 855
    ClientSetIgnoreFriendResponse = 856
    ClientGetAppOwnershipTicket = 857
    ClientGetAppOwnershipTicketResponse = 858
    ClientGetLobbyListResponse = 860
    ClientVTTCert = 863
    ClientAppInfoUpdate = 866
    ClientAppInfoChanges = 867
    ClientServerList = 880
    ClientEmailChangeResponse = 891
    ClientSecretQAChangeResponse = 892
    ClientDRMBlobRequest = 896
    ClientDRMBlobResponse = 897

    BaseGameServer = 900
    GSDisconnectNotice = 901
    GSStatus = 903
    GSUserPlaying = 905
    GSStatus2 = 906
    GSStatusUpdate_Unused = 907
    GSServerType = 908
    GSPlayerList = 909
    GSGetUserAchievementStatus = 910
    GSGetUserAchievementStatusResponse = 911
    GSGetPlayStats = 918
    GSGetPlayStatsResponse = 919
    GSGetUserGroupStatus = 920
    AMGetUserGroupStatus = 921
    AMGetUserGroupStatusResponse = 922
    GSGetUserGroupStatusResponse = 923
    GSGetReputation = 936
    GSGetReputationResponse = 937
    GSAssociateWithClan = 938
    GSAssociateWithClanResponse = 939
    GSComputeNewPlayerCompatibility = 940
    GSComputeNewPlayerCompatibilityResponse = 941

    BaseAdmin = 1000
    AdminCmd = 1000
    AdminCmdResponse = 1004
    AdminLogListenRequest = 1005
    AdminLogEvent = 1006
    UniverseData = 1010
    AdminSpew = 1019
    AdminConsoleTitle = 1020
    AdminGCSpew = 1023
    AdminGCCommand = 1024
    AdminGCGetCommandList = 1025
    AdminGCGetCommandListResponse = 1026
    FBSConnectionData = 1027
    AdminMsgSpew = 1028

    BaseFBS = 1100
    FBSReqVersion = 1100
    FBSVersionInfo = 1101
    FBSForceRefresh = 1102
    FBSForceBounce = 1103
    FBSDeployPackage = 1104
    FBSDeployResponse = 1105
    FBSUpdateBootstrapper = 1106
    FBSSetState = 1107
    FBSApplyOSUpdates = 1108
    FBSRunCMDScript = 1109
    FBSRebootBox = 1110
    FBSSetBigBrotherMode = 1111
    FBSMinidumpServer = 1112
    FBSDeployHotFixPackage = 1114
    FBSDeployHotFixResponse = 1115
    FBSDownloadHotFix = 1116
    FBSDownloadHotFixResponse = 1117
    FBSUpdateTargetConfigFile = 1118
    FBSApplyAccountCred = 1119
    FBSApplyAccountCredResponse = 1120
    FBSSetShellCount = 1121
    FBSTerminateShell = 1122
    FBSQueryGMForRequest = 1123
    FBSQueryGMResponse = 1124
    FBSTerminateZombies = 1125
    FBSInfoFromBootstrapper = 1126
    FBSRebootBoxResponse = 1127
    FBSBootstrapperPackageRequest = 1128
    FBSBootstrapperPackageResponse = 1129
    FBSBootstrapperGetPackageChunk = 1130
    FBSBootstrapperGetPackageChunkResponse = 1131
    FBSBootstrapperPackageTransferProgress = 1132
    FBSRestartBootstrapper = 1133

    BaseFileXfer = 1200
    FileXferRequest = 1200
    FileXferResponse = 1201
    FileXferData = 1202
    FileXferEnd = 1203
    FileXferDataAck = 1204

    BaseChannelAuth = 1300
    ChannelAuthChallenge = 1300
    ChannelAuthResponse = 1301
    ChannelAuthResult = 1302
    ChannelEncryptRequest = 1303
    ChannelEncryptResponse = 1304
    ChannelEncryptResult = 1305

    BaseBS = 1400
    BSPurchaseStart = 1401
    BSInitPayPalTxn = 1408
    BSInitPayPalTxnResponse = 1409
    BSGetPayPalUserInfo = 1410
    BSGetPayPalUserInfoResponse = 1411
    BSPaymentInstrBan = 1417
    BSPaymentInstrBanResponse = 1418
    BSInitGCBankXferTxn = 1421
    BSInitGCBankXferTxnResponse = 1422
    BSCommitGCTxn = 1425
    BSQueryTransactionStatus = 1426
    BSQueryTransactionStatusResponse = 1427
    BSQueryPaymentInstUsage = 1431
    BSQueryPaymentInstResponse = 1432
    BSQueryTxnExtendedInfo = 1433
    BSQueryTxnExtendedInfoResponse = 1434
    BSUpdateConversionRates = 1435
    BSPurchaseRunFraudChecks = 1437
    BSPurchaseRunFraudChecksResponse = 1438
    BSQueryBankInformation = 1440
    BSQueryBankInformationResponse = 1441
    BSValidateXsollaSignature = 1445
    BSValidateXsollaSignatureResponse = 1446
    BSQiwiWalletInvoice = 1448
    BSQiwiWalletInvoiceResponse = 1449
    BSUpdateInventoryFromProPack = 1450
    BSUpdateInventoryFromProPackResponse = 1451
    BSSendShippingRequest = 1452
    BSSendShippingRequestResponse = 1453
    BSGetProPackOrderStatus = 1454
    BSGetProPackOrderStatusResponse = 1455
    BSCheckJobRunning = 1456
    BSCheckJobRunningResponse = 1457
    BSResetPackagePurchaseRateLimit = 1458
    BSResetPackagePurchaseRateLimitResponse = 1459
    BSUpdatePaymentData = 1460
    BSUpdatePaymentDataResponse = 1461
    BSGetBillingAddress = 1462
    BSGetBillingAddressResponse = 1463
    BSGetCreditCardInfo = 1464
    BSGetCreditCardInfoResponse = 1465
    BSRemoveExpiredPaymentData = 1468
    BSRemoveExpiredPaymentDataResponse = 1469
    BSConvertToCurrentKeys = 1470
    BSConvertToCurrentKeysResponse = 1471
    BSInitPurchase = 1472
    BSInitPurchaseResponse = 1473
    BSCompletePurchase = 1474
    BSCompletePurchaseResponse = 1475
    BSPruneCardUsageStats = 1476
    BSPruneCardUsageStatsResponse = 1477
    BSStoreBankInformation = 1478
    BSStoreBankInformationResponse = 1479
    BSVerifyPOSAKey = 1480
    BSVerifyPOSAKeyResponse = 1481
    BSReverseRedeemPOSAKey = 1482
    BSReverseRedeemPOSAKeyResponse = 1483
    BSQueryFindCreditCard = 1484
    BSQueryFindCreditCardResponse = 1485
    BSStatusInquiryPOSAKey = 1486
    BSStatusInquiryPOSAKeyResponse = 1487
    BSValidateMoPaySignature = 1488
    BSValidateMoPaySignatureResponse = 1489
    BSMoPayConfirmProductDelivery = 1490
    BSMoPayConfirmProductDeliveryResponse = 1491
    BSGenerateMoPayMD5 = 1492
    BSGenerateMoPayMD5Response = 1493
    BSBoaCompraConfirmProductDelivery = 1494
    BSBoaCompraConfirmProductDeliveryResponse = 1495
    BSGenerateBoaCompraMD5 = 1496
    BSGenerateBoaCompraMD5Response = 1497
    BSCommitWPTxn = 1498

    BaseATS = 1500
    ATSStartStressTest = 1501
    ATSStopStressTest = 1502
    ATSRunFailServerTest = 1503
    ATSUFSPerfTestTask = 1504
    ATSUFSPerfTestResponse = 1505
    ATSCycleTCM = 1506
    ATSInitDRMSStressTest = 1507
    ATSCallTest = 1508
    ATSCallTestReply = 1509
    ATSStartExternalStress = 1510
    ATSExternalStressJobStart = 1511
    ATSExternalStressJobQueued = 1512
    ATSExternalStressJobRunning = 1513
    ATSExternalStressJobStopped = 1514
    ATSExternalStressJobStopAll = 1515
    ATSExternalStressActionResult = 1516
    ATSStarted = 1517
    ATSCSPerfTestTask = 1518
    ATSCSPerfTestResponse = 1519

    BaseDP = 1600
    DPSetPublishingState = 1601
    DPUniquePlayersStat = 1603
    DPStreamingUniquePlayersStat = 1604
    DPVacInfractionStats = 1605
    DPVacBanStats = 1606
    DPBlockingStats = 1607
    DPNatTraversalStats = 1608
    DPVacCertBanStats = 1610
    DPVacCafeBanStats = 1611
    DPCloudStats = 1612
    DPAchievementStats = 1613
    DPAccountCreationStats = 1614
    DPGetPlayerCount = 1615
    DPGetPlayerCountResponse = 1616
    DPGameServersPlayersStats = 1617
    DPFacebookStatistics = 1619
    ClientDPCheckSpecialSurvey = 1620
    ClientDPCheckSpecialSurveyResponse = 1621
    ClientDPSendSpecialSurveyResponse = 1622
    ClientDPSendSpecialSurveyResponseReply = 1623
    DPStoreSaleStatistics = 1624
    ClientDPUpdateAppJobReport = 1625
    DPUpdateContentEvent = 1626
    DPPartnerMicroTxns = 1628
    DPPartnerMicroTxnsResponse = 1629
    ClientDPContentStatsReport = 1630
    DPVRUniquePlayersStat = 1631

    BaseCM = 1700
    CMSetAllowState = 1701
    CMSpewAllowState = 1702

    BaseGC = 2200
    GCCmdRevive = 2203
    GCCmdDown = 2206
    GCCmdDeploy = 2207
    GCCmdDeployResponse = 2208
    GCCmdSwitch = 2209
    AMRefreshSessions = 2210
    GCAchievementAwarded = 2212
    GCSystemMessage = 2213
    GCCmdStatus = 2216
    GCInterAppMessage = 2219
    GCGetEmailTemplate = 2220
    GCGetEmailTemplateResponse = 2221
    GCHRelay = 2222
    GCHRelayToClient = 2223
    GCHUpdateSession = 2224
    GCHRequestUpdateSession = 2225
    GCHRequestStatus = 2226
    GCHRequestStatusResponse = 2227
    GCHAccountVacStatusChange = 2228
    GCHSpawnGC = 2229
    GCHSpawnGCResponse = 2230
    GCHKillGC = 2231
    GCHKillGCResponse = 2232
    GCHAccountTradeBanStatusChange = 2233
    GCHAccountLockStatusChange = 2234
    GCHVacVerificationChange = 2235
    GCHAccountPhoneNumberChange = 2236
    GCHAccountTwoFactorChange = 2237

    BaseP2P = 2500
    P2PIntroducerMessage = 2502

    BaseSM = 2900
    SMExpensiveReport = 2902
    SMHourlyReport = 2903
    SMFishingReport = 2904
    SMPartitionRenames = 2905
    SMMonitorSpace = 2906

    BaseTest = 3000
    FailServer = 3000
    JobHeartbeatTest = 3001
    JobHeartbeatTestResponse = 3002

    BaseFTSRange = 3100

    BaseCCSRange = 3150
    CCSDeleteAllCommentsByAuthor = 3161
    CCSDeleteAllCommentsByAuthorResponse = 3162

    BaseLBSRange = 3200
    LBSSetScore = 3201
    LBSSetScoreResponse = 3202
    LBSFindOrCreateLB = 3203
    LBSFindOrCreateLBResponse = 3204
    LBSGetLBEntries = 3205
    LBSGetLBEntriesResponse = 3206
    LBSGetLBList = 3207
    LBSGetLBListResponse = 3208
    LBSSetLBDetails = 3209
    LBSDeleteLB = 3210
    LBSDeleteLBEntry = 3211
    LBSResetLB = 3212
    LBSResetLBResponse = 3213
    LBSDeleteLBResponse = 3214

    BaseOGS = 3400
    OGSBeginSession = 3401
    OGSBeginSessionResponse = 3402
    OGSEndSession = 3403
    OGSEndSessionResponse = 3404
    OGSWriteAppSessionRow = 3406

    BaseBRP = 3600
    BRPStartShippingJobs = 3601
    BRPProcessUSBankReports = 3602
    BRPProcessGCReports = 3603
    BRPProcessPPReports = 3604
    BRPCommitGC = 3607
    BRPCommitGCResponse = 3608
    BRPFindHungTransactions = 3609
    BRPCheckFinanceCloseOutDate = 3610
    BRPProcessLicenses = 3611
    BRPProcessLicensesResponse = 3612
    BRPRemoveExpiredPaymentData = 3613
    BRPRemoveExpiredPaymentDataResponse = 3614
    BRPConvertToCurrentKeys = 3615
    BRPConvertToCurrentKeysResponse = 3616
    BRPPruneCardUsageStats = 3617
    BRPPruneCardUsageStatsResponse = 3618
    BRPCheckActivationCodes = 3619
    BRPCheckActivationCodesResponse = 3620
    BRPCommitWP = 3621
    BRPCommitWPResponse = 3622
    BRPProcessWPReports = 3623
    BRPProcessPaymentRules = 3624
    BRPProcessPartnerPayments = 3625
    BRPCheckSettlementReports = 3626
    BRPPostTaxToAvalara = 3628
    BRPPostTransactionTax = 3629
    BRPPostTransactionTaxResponse = 3630
    BRPProcessIMReports = 3631

    BaseAMRange2 = 4000
    AMCreateChat = 4001
    AMCreateChatResponse = 4002
    AMSetProfileURL = 4005
    AMGetAccountEmailAddress = 4006
    AMGetAccountEmailAddressResponse = 4007
    AMRequestClanData = 4008
    AMRouteToClients = 4009
    AMLeaveClan = 4010
    AMClanPermissions = 4011
    AMClanPermissionsResponse = 4012
    AMCreateClanEvent = 4013
    AMCreateClanEventResponse = 4014
    AMUpdateClanEvent = 4015
    AMUpdateClanEventResponse = 4016
    AMGetClanEvents = 4017
    AMGetClanEventsResponse = 4018
    AMDeleteClanEvent = 4019
    AMDeleteClanEventResponse = 4020
    AMSetClanPermissionSettings = 4021
    AMSetClanPermissionSettingsResponse = 4022
    AMGetClanPermissionSettings = 4023
    AMGetClanPermissionSettingsResponse = 4024
    AMPublishChatRoomInfo = 4025
    ClientChatRoomInfo = 4026
    AMGetClanHistory = 4039
    AMGetClanHistoryResponse = 4040
    AMGetClanPermissionBits = 4041
    AMGetClanPermissionBitsResponse = 4042
    AMSetClanPermissionBits = 4043
    AMSetClanPermissionBitsResponse = 4044
    AMSessionInfoRequest = 4045
    AMSessionInfoResponse = 4046
    AMValidateWGToken = 4047
    AMGetSingleClanEvent = 4048
    AMGetSingleClanEventResponse = 4049
    AMGetClanRank = 4050
    AMGetClanRankResponse = 4051
    AMSetClanRank = 4052
    AMSetClanRankResponse = 4053
    AMGetClanPOTW = 4054
    AMGetClanPOTWResponse = 4055
    AMSetClanPOTW = 4056
    AMSetClanPOTWResponse = 4057
    AMDumpUser = 4059
    AMKickUserFromClan = 4060
    AMAddFounderToClan = 4061
    AMValidateWGTokenResponse = 4062
    AMSetCommunityState = 4063
    AMSetAccountDetails = 4064
    AMGetChatBanList = 4065
    AMGetChatBanListResponse = 4066
    AMUnBanFromChat = 4067
    AMSetClanDetails = 4068
    AMGetAccountLinks = 4069
    AMGetAccountLinksResponse = 4070
    AMSetAccountLinks = 4071
    AMSetAccountLinksResponse = 4072
    AMGetUserGameStats = 4073
    AMGetUserGameStatsResponse = 4074
    AMCheckClanMembership = 4075
    AMGetClanMembers = 4076
    AMGetClanMembersResponse = 4077
    AMJoinPublicClan = 4078
    AMNotifyChatOfClanChange = 4079
    AMResubmitPurchase = 4080
    AMAddFriend = 4081
    AMAddFriendResponse = 4082
    AMRemoveFriend = 4083
    AMDumpClan = 4084
    AMChangeClanOwner = 4085
    AMCancelEasyCollect = 4086
    AMCancelEasyCollectResponse = 4087
    AMClansInCommon = 4090
    AMClansInCommonResponse = 4091
    AMIsValidAccountID = 4092
    AMConvertClan = 4093
    AMWipeFriendsList = 4095
    AMSetIgnored = 4096
    AMClansInCommonCountResponse = 4097
    AMFriendsList = 4098
    AMFriendsListResponse = 4099
    AMFriendsInCommon = 4100
    AMFriendsInCommonResponse = 4101
    AMFriendsInCommonCountResponse = 4102
    AMClansInCommonCount = 4103
    AMChallengeVerdict = 4104
    AMChallengeNotification = 4105
    AMFindGSByIP = 4106
    AMFoundGSByIP = 4107
    AMGiftRevoked = 4108
    AMCreateAccountRecord = 4109
    AMUserClanList = 4110
    AMUserClanListResponse = 4111
    AMGetAccountDetails2 = 4112
    AMGetAccountDetailsResponse2 = 4113
    AMSetCommunityProfileSettings = 4114
    AMSetCommunityProfileSettingsResponse = 4115
    AMGetCommunityPrivacyState = 4116
    AMGetCommunityPrivacyStateResponse = 4117
    AMCheckClanInviteRateLimiting = 4118
    AMGetUserAchievementStatus = 4119
    AMGetIgnored = 4120
    AMGetIgnoredResponse = 4121
    AMSetIgnoredResponse = 4122
    AMSetFriendRelationshipNone = 4123
    AMGetFriendRelationship = 4124
    AMGetFriendRelationshipResponse = 4125
    AMServiceModulesCache = 4126
    AMServiceModulesCall = 4127
    AMServiceModulesCallResponse = 4128
    AMGetCaptchaDataForIP = 4129
    AMGetCaptchaDataForIPResponse = 4130
    AMValidateCaptchaDataForIP = 4131
    AMValidateCaptchaDataForIPResponse = 4132
    AMTrackFailedAuthByIP = 4133
    AMGetCaptchaDataByGID = 4134
    AMGetCaptchaDataByGIDResponse = 4135
    CommunityAddFriendNews = 4140
    AMFindClanUser = 4143
    AMFindClanUserResponse = 4144
    AMBanFromChat = 4145
    AMGetUserNewsSubscriptions = 4147
    AMGetUserNewsSubscriptionsResponse = 4148
    AMSetUserNewsSubscriptions = 4149
    AMSendQueuedEmails = 4152
    AMSetLicenseFlags = 4153
    CommunityDeleteUserNews = 4155
    AMAllowUserFilesRequest = 4156
    AMAllowUserFilesResponse = 4157
    AMGetAccountStatus = 4158
    AMGetAccountStatusResponse = 4159
    AMEditBanReason = 4160
    AMCheckClanMembershipResponse = 4161
    AMProbeClanMembershipList = 4162
    AMProbeClanMembershipListResponse = 4163
    AMGetFriendsLobbies = 4165
    AMGetFriendsLobbiesResponse = 4166
    AMGetUserFriendNewsResponse = 4172
    CommunityGetUserFriendNews = 4173
    AMGetUserClansNewsResponse = 4174
    AMGetUserClansNews = 4175
    AMGetPreviousCBAccount = 4184
    AMGetPreviousCBAccountResponse = 4185
    AMGetUserLicenseHistory = 4190
    AMGetUserLicenseHistoryResponse = 4191
    AMSupportChangePassword = 4194
    AMSupportChangeEmail = 4195
    AMResetUserVerificationGSByIP = 4197
    AMUpdateGSPlayStats = 4198
    AMSupportEnableOrDisable = 4199
    AMGetPurchaseStatus = 4206
    AMSupportIsAccountEnabled = 4209
    AMSupportIsAccountEnabledResponse = 4210
    AMGetUserStats = 4211
    AMSupportKickSession = 4212
    AMGSSearch = 4213
    MarketingMessageUpdate = 4216
    AMRouteFriendMsg = 4219
    AMTicketAuthRequestOrResponse = 4220
    AMVerifyDepotManagementRights = 4222
    AMVerifyDepotManagementRightsResponse = 4223
    AMAddFreeLicense = 4224
    AMValidateEmailLink = 4231
    AMValidateEmailLinkResponse = 4232
    AMStoreUserStats = 4236
    AMDeleteStoredCard = 4241
    AMRevokeLegacyGameKeys = 4242
    AMGetWalletDetails = 4244
    AMGetWalletDetailsResponse = 4245
    AMDeleteStoredPaymentInfo = 4246
    AMGetStoredPaymentSummary = 4247
    AMGetStoredPaymentSummaryResponse = 4248
    AMGetWalletConversionRate = 4249
    AMGetWalletConversionRateResponse = 4250
    AMConvertWallet = 4251
    AMConvertWalletResponse = 4252
    AMSetPreApproval = 4255
    AMSetPreApprovalResponse = 4256
    AMCreateRefund = 4258
    AMCreateRefundResponse = 4259
    AMCreateChargeback = 4260
    AMCreateChargebackResponse = 4261
    AMCreateDispute = 4262
    AMCreateDisputeResponse = 4263
    AMClearDispute = 4264
    AMClearDisputeResponse = 4265
    AMPlayerNicknameList = 4266
    AMPlayerNicknameListResponse = 4267
    AMSetDRMTestConfig = 4268
    AMGetUserCurrentGameInfo = 4269
    AMGetUserCurrentGameInfoResponse = 4270
    AMGetGSPlayerList = 4271
    AMGetGSPlayerListResponse = 4272
    AMGetGameMembers = 4276
    AMGetGameMembersResponse = 4277
    AMGetSteamIDForMicroTxn = 4278
    AMGetSteamIDForMicroTxnResponse = 4279
    AMAddPublisherUser = 4280
    AMRemovePublisherUser = 4281
    AMGetUserLicenseList = 4282
    AMGetUserLicenseListResponse = 4283
    AMReloadGameGroupPolicy = 4284
    AMAddFreeLicenseResponse = 4285
    AMVACStatusUpdate = 4286
    AMGetAccountDetails = 4287
    AMGetAccountDetailsResponse = 4288
    AMGetPlayerLinkDetails = 4289
    AMGetPlayerLinkDetailsResponse = 4290
    AMGetAccountFlagsForWGSpoofing = 4294
    AMGetAccountFlagsForWGSpoofingResponse = 4295
    AMGetClanOfficers = 4298
    AMGetClanOfficersResponse = 4299
    AMNameChange = 4300
    AMGetNameHistory = 4301
    AMGetNameHistoryResponse = 4302
    AMUpdateProviderStatus = 4305
    AMSupportRemoveAccountSecurity = 4307
    AMIsAccountInCaptchaGracePeriod = 4308
    AMIsAccountInCaptchaGracePeriodResponse = 4309
    AMAccountPS3Unlink = 4310
    AMAccountPS3UnlinkResponse = 4311
    AMStoreUserStatsResponse = 4312
    AMGetAccountPSNInfo = 4313
    AMGetAccountPSNInfoResponse = 4314
    AMAuthenticatedPlayerList = 4315
    AMGetUserGifts = 4316
    AMGetUserGiftsResponse = 4317
    AMTransferLockedGifts = 4320
    AMTransferLockedGiftsResponse = 4321
    AMPlayerHostedOnGameServer = 4322
    AMGetAccountBanInfo = 4323
    AMGetAccountBanInfoResponse = 4324
    AMRecordBanEnforcement = 4325
    AMRollbackGiftTransfer = 4326
    AMRollbackGiftTransferResponse = 4327
    AMHandlePendingTransaction = 4328
    AMRequestClanDetails = 4329
    AMDeleteStoredPaypalAgreement = 4330
    AMGameServerUpdate = 4331
    AMGameServerRemove = 4332
    AMGetPaypalAgreements = 4333
    AMGetPaypalAgreementsResponse = 4334
    AMGameServerPlayerCompatibilityCheck = 4335
    AMGameServerPlayerCompatibilityCheckResponse = 4336
    AMRenewLicense = 4337
    AMGetAccountCommunityBanInfo = 4338
    AMGetAccountCommunityBanInfoResponse = 4339
    AMGameServerAccountChangePassword = 4340
    AMGameServerAccountDeleteAccount = 4341
    AMRenewAgreement = 4342
    AMXsollaPayment = 4344
    AMXsollaPaymentResponse = 4345
    AMAcctAllowedToPurchase = 4346
    AMAcctAllowedToPurchaseResponse = 4347
    AMSwapKioskDeposit = 4348
    AMSwapKioskDepositResponse = 4349
    AMSetUserGiftUnowned = 4350
    AMSetUserGiftUnownedResponse = 4351
    AMClaimUnownedUserGift = 4352
    AMClaimUnownedUserGiftResponse = 4353
    AMSetClanName = 4354
    AMSetClanNameResponse = 4355
    AMGrantCoupon = 4356
    AMGrantCouponResponse = 4357
    AMIsPackageRestrictedInUserCountry = 4358
    AMIsPackageRestrictedInUserCountryResponse = 4359
    AMHandlePendingTransactionResponse = 4360
    AMGrantGuestPasses2 = 4361
    AMGrantGuestPasses2Response = 4362
    AMSessionQuery = 4363
    AMSessionQueryResponse = 4364
    AMGetPlayerBanDetails = 4365
    AMGetPlayerBanDetailsResponse = 4366
    AMFinalizePurchase = 4367
    AMFinalizePurchaseResponse = 4368
    AMPersonaChangeResponse = 4372
    AMGetClanDetailsForForumCreation = 4373
    AMGetClanDetailsForForumCreationResponse = 4374
    AMGetPendingNotificationCount = 4375
    AMGetPendingNotificationCountResponse = 4376
    AMPasswordHashUpgrade = 4377
    AMMoPayPayment = 4378
    AMMoPayPaymentResponse = 4379
    AMBoaCompraPayment = 4380
    AMBoaCompraPaymentResponse = 4381
    AMExpireCaptchaByGID = 4382
    AMCompleteExternalPurchase = 4383
    AMCompleteExternalPurchaseResponse = 4384
    AMResolveNegativeWalletCredits = 4385
    AMResolveNegativeWalletCreditsResponse = 4386
    AMPayelpPayment = 4387
    AMPayelpPaymentResponse = 4388
    AMPlayerGetClanBasicDetails = 4389
    AMPlayerGetClanBasicDetailsResponse = 4390
    AMMOLPayment = 4391
    AMMOLPaymentResponse = 4392
    GetUserIPCountry = 4393
    GetUserIPCountryResponse = 4394
    NotificationOfSuspiciousActivity = 4395
    AMDegicaPayment = 4396
    AMDegicaPaymentResponse = 4397
    AMEClubPayment = 4398
    AMEClubPaymentResponse = 4399
    AMPayPalPaymentsHubPayment = 4400
    AMPayPalPaymentsHubPaymentResponse = 4401
    AMTwoFactorRecoverAuthenticatorRequest = 4402
    AMTwoFactorRecoverAuthenticatorResponse = 4403
    AMSmart2PayPayment = 4404
    AMSmart2PayPaymentResponse = 4405
    AMValidatePasswordResetCodeAndSendSmsRequest = 4406
    AMValidatePasswordResetCodeAndSendSmsResponse = 4407
    AMGetAccountResetDetailsRequest = 4408
    AMGetAccountResetDetailsResponse = 4409
    AMBitPayPayment = 4410
    AMBitPayPaymentResponse = 4411
    AMSendAccountInfoUpdate = 4412

    BasePSRange = 5000
    PSCreateShoppingCart = 5001
    PSCreateShoppingCartResponse = 5002
    PSIsValidShoppingCart = 5003
    PSIsValidShoppingCartResponse = 5004
    PSAddPackageToShoppingCart = 5005
    PSAddPackageToShoppingCartResponse = 5006
    PSRemoveLineItemFromShoppingCart = 5007
    PSRemoveLineItemFromShoppingCartResponse = 5008
    PSGetShoppingCartContents = 5009
    PSGetShoppingCartContentsResponse = 5010
    PSAddWalletCreditToShoppingCart = 5011
    PSAddWalletCreditToShoppingCartResponse = 5012

    BaseUFSRange = 5200
    ClientUFSUploadFileRequest = 5202
    ClientUFSUploadFileResponse = 5203
    ClientUFSUploadFileChunk = 5204
    ClientUFSUploadFileFinished = 5205
    ClientUFSGetFileListForApp = 5206
    ClientUFSGetFileListForAppResponse = 5207
    ClientUFSLoginRequest = 5213
    ClientUFSLoginResponse = 5214
    UFSReloadPartitionInfo = 5215
    ClientUFSTransferHeartbeat = 5216
    UFSSynchronizeFile = 5217
    UFSSynchronizeFileResponse = 5218
    ClientUFSDeleteFileRequest = 5219
    ClientUFSDeleteFileResponse = 5220
    UFSDownloadRequest = 5221
    UFSDownloadResponse = 5222
    UFSDownloadChunk = 5223
    ClientUFSGetUGCDetails = 5226
    ClientUFSGetUGCDetailsResponse = 5227
    UFSUpdateFileFlags = 5228
    UFSUpdateFileFlagsResponse = 5229
    ClientUFSGetSingleFileInfo = 5230
    ClientUFSGetSingleFileInfoResponse = 5231
    ClientUFSShareFile = 5232
    ClientUFSShareFileResponse = 5233
    UFSReloadAccount = 5234
    UFSReloadAccountResponse = 5235
    UFSUpdateRecordBatched = 5236
    UFSUpdateRecordBatchedResponse = 5237
    UFSMigrateFile = 5238
    UFSMigrateFileResponse = 5239
    UFSGetUGCURLs = 5240
    UFSGetUGCURLsResponse = 5241
    UFSHttpUploadFileFinishRequest = 5242
    UFSHttpUploadFileFinishResponse = 5243
    UFSDownloadStartRequest = 5244
    UFSDownloadStartResponse = 5245
    UFSDownloadChunkRequest = 5246
    UFSDownloadChunkResponse = 5247
    UFSDownloadFinishRequest = 5248
    UFSDownloadFinishResponse = 5249
    UFSFlushURLCache = 5250
    UFSUploadCommit = 5251
    UFSUploadCommitResponse = 5252
    UFSMigrateFileAppID = 5253
    UFSMigrateFileAppIDResponse = 5254

    BaseClient2 = 5400
    ClientRequestForgottenPasswordEmail = 5401
    ClientRequestForgottenPasswordEmailResponse = 5402
    ClientCreateAccountResponse = 5403
    ClientResetForgottenPassword = 5404
    ClientResetForgottenPasswordResponse = 5405
    ClientCreateAccount2 = 5406
    ClientInformOfResetForgottenPassword = 5407
    ClientInformOfResetForgottenPasswordResponse = 5408
    ClientGamesPlayedWithDataBlob = 5410
    ClientUpdateUserGameInfo = 5411
    ClientFileToDownload = 5412
    ClientFileToDownloadResponse = 5413
    ClientLBSSetScore = 5414
    ClientLBSSetScoreResponse = 5415
    ClientLBSFindOrCreateLB = 5416
    ClientLBSFindOrCreateLBResponse = 5417
    ClientLBSGetLBEntries = 5418
    ClientLBSGetLBEntriesResponse = 5419
    ClientChatDeclined = 5426
    ClientFriendMsgIncoming = 5427
    ClientTicketAuthComplete = 5429
    ClientIsLimitedAccount = 5430
    ClientRequestAuthList = 5431
    ClientAuthList = 5432
    ClientStat = 5433
    ClientP2PConnectionInfo = 5434
    ClientP2PConnectionFailInfo = 5435
    ClientGetDepotDecryptionKey = 5438
    ClientGetDepotDecryptionKeyResponse = 5439
    GSPerformHardwareSurvey = 5440
    ClientEnableTestLicense = 5443
    ClientEnableTestLicenseResponse = 5444
    ClientDisableTestLicense = 5445
    ClientDisableTestLicenseResponse = 5446
    ClientRequestValidationMail = 5448
    ClientRequestValidationMailResponse = 5449
    ClientCheckAppBetaPassword = 5450
    ClientCheckAppBetaPasswordResponse = 5451
    ClientToGC = 5452
    ClientFromGC = 5453
    ClientRequestChangeMail = 5454
    ClientRequestChangeMailResponse = 5455
    ClientEmailAddrInfo = 5456
    ClientPasswordChange3 = 5457
    ClientEmailChange3 = 5458
    ClientPersonalQAChange3 = 5459
    ClientResetForgottenPassword3 = 5460
    ClientRequestForgottenPasswordEmail3 = 5461

    ClientNewLoginKey = 5463
    ClientNewLoginKeyAccepted = 5464

    ClientStoreUserStats2 = 5466
    ClientStatsUpdated = 5467
    ClientActivateOEMLicense = 5468
    ClientRegisterOEMMachine = 5469
    ClientRegisterOEMMachineResponse = 5470
    ClientRequestedClientStats = 5480
    ClientStat2Int32 = 5481
    ClientStat2 = 5482
    ClientVerifyPassword = 5483
    ClientVerifyPasswordResponse = 5484
    ClientDRMDownloadRequest = 5485
    ClientDRMDownloadResponse = 5486
    ClientDRMFinalResult = 5487
    ClientGetFriendsWhoPlayGame = 5488
    ClientGetFriendsWhoPlayGameResponse = 5489
    ClientOGSBeginSession = 5490
    ClientOGSBeginSessionResponse = 5491
    ClientOGSEndSession = 5492
    ClientOGSEndSessionResponse = 5493
    ClientOGSWriteRow = 5494
    ClientDRMTest = 5495
    ClientDRMTestResult = 5496
    ClientServerUnavailable = 5500
    ClientServersAvailable = 5501
    ClientRegisterAuthTicketWithCM = 5502
    ClientGCMsgFailed = 5503
    ClientMicroTxnAuthRequest = 5504
    ClientMicroTxnAuthorize = 5505
    ClientMicroTxnAuthorizeResponse = 5506
    ClientAppMinutesPlayedData = 5507
    ClientGetMicroTxnInfo = 5508
    ClientGetMicroTxnInfoResponse = 5509
    ClientMarketingMessageUpdate2 = 5510
    ClientDeregisterWithServer = 5511
    ClientSubscribeToPersonaFeed = 5512
    ClientLogon = 5514
    ClientGetClientDetails = 5515
    ClientGetClientDetailsResponse = 5516
    ClientReportOverlayDetourFailure = 5517
    ClientGetClientAppList = 5518
    ClientGetClientAppListResponse = 5519
    ClientInstallClientApp = 5520
    ClientInstallClientAppResponse = 5521
    ClientUninstallClientApp = 5522
    ClientUninstallClientAppResponse = 5523
    ClientSetClientAppUpdateState = 5524
    ClientSetClientAppUpdateStateResponse = 5525
    ClientRequestEncryptedAppTicket = 5526
    ClientRequestEncryptedAppTicketResponse = 5527
    ClientWalletInfoUpdate = 5528
    ClientLBSSetUGC = 5529
    ClientLBSSetUGCResponse = 5530
    ClientAMGetClanOfficers = 5531
    ClientAMGetClanOfficersResponse = 5532

    ClientFriendProfileInfo = 5535
    ClientFriendProfileInfoResponse = 5536
    ClientUpdateMachineAuth = 5537
    ClientUpdateMachineAuthResponse = 5538
    ClientReadMachineAuth = 5539
    ClientReadMachineAuthResponse = 5540
    ClientRequestMachineAuth = 5541
    ClientRequestMachineAuthResponse = 5542
    ClientScreenshotsChanged = 5543
    ClientEmailChange4 = 5544
    ClientEmailChangeResponse4 = 5545
    ClientGetCDNAuthToken = 5546
    ClientGetCDNAuthTokenResponse = 5547
    ClientDownloadRateStatistics = 5548
    ClientRequestAccountData = 5549
    ClientRequestAccountDataResponse = 5550
    ClientResetForgottenPassword4 = 5551
    ClientHideFriend = 5552
    ClientFriendsGroupsList = 5553
    ClientGetClanActivityCounts = 5554
    ClientGetClanActivityCountsResponse = 5555
    ClientOGSReportString = 5556
    ClientOGSReportBug = 5557
    ClientSentLogs = 5558
    ClientLogonGameServer = 5559
    AMClientCreateFriendsGroup = 5560
    AMClientCreateFriendsGroupResponse = 5561
    AMClientDeleteFriendsGroup = 5562
    AMClientDeleteFriendsGroupResponse = 5563
    AMClientRenameFriendsGroup = 5564
    AMClientRenameFriendsGroupResponse = 5565
    AMClientAddFriendToGroup = 5566
    AMClientAddFriendToGroupResponse = 5567
    AMClientRemoveFriendFromGroup = 5568
    AMClientRemoveFriendFromGroupResponse = 5569
    ClientAMGetPersonaNameHistory = 5570
    ClientAMGetPersonaNameHistoryResponse = 5571
    ClientRequestFreeLicense = 5572
    ClientRequestFreeLicenseResponse = 5573
    ClientDRMDownloadRequestWithCrashData = 5574
    ClientAuthListAck = 5575
    ClientItemAnnouncements = 5576
    ClientRequestItemAnnouncements = 5577
    ClientFriendMsgEchoToSender = 5578

    ClientOGSGameServerPingSample = 5581
    ClientCommentNotifications = 5582
    ClientRequestCommentNotifications = 5583
    ClientPersonaChangeResponse = 5584
    ClientRequestWebAPIAuthenticateUserNonce = 5585
    ClientRequestWebAPIAuthenticateUserNonceResponse = 5586
    ClientPlayerNicknameList = 5587
    AMClientSetPlayerNickname = 5588
    AMClientSetPlayerNicknameResponse = 5589

    ClientCreateAccountProto = 5590
    ClientCreateAccountProtoResponse = 5591
    ClientGetNumberOfCurrentPlayersDP = 5592
    ClientGetNumberOfCurrentPlayersDPResponse = 5593
    ClientServiceMethod = 5594
    ClientServiceMethodResponse = 5595
    ClientFriendUserStatusPublished = 5596
    ClientCurrentUIMode = 5597
    ClientVanityURLChangedNotification = 5598
    ClientUserNotifications = 5599

    BaseDFS = 5600
    DFSGetFile = 5601
    DFSInstallLocalFile = 5602
    DFSConnection = 5603
    DFSConnectionReply = 5604
    ClientDFSAuthenticateRequest = 5605
    ClientDFSAuthenticateResponse = 5606
    ClientDFSEndSession = 5607
    DFSPurgeFile = 5608
    DFSRouteFile = 5609
    DFSGetFileFromServer = 5610
    DFSAcceptedResponse = 5611
    DFSRequestPingback = 5612
    DFSRecvTransmitFile = 5613
    DFSSendTransmitFile = 5614
    DFSRequestPingback2 = 5615
    DFSResponsePingback2 = 5616
    ClientDFSDownloadStatus = 5617
    DFSStartTransfer = 5618
    DFSTransferComplete = 5619
    DFSRouteFileResponse = 5620
    ClientNetworkingCertRequest = 5621
    ClientNetworkingCertRequestResponse = 5622

    BaseMDS = 5800

    AMToMDSGetDepotDecryptionKey = 5812
    MDSToAMGetDepotDecryptionKeyResponse = 5813

    MDSContentServerConfigRequest = 5827
    MDSContentServerConfig = 5828
    MDSGetDepotManifest = 5829
    MDSGetDepotManifestResponse = 5830
    MDSGetDepotManifestChunk = 5831
    MDSGetDepotChunk = 5832
    MDSGetDepotChunkResponse = 5833
    MDSGetDepotChunkChunk = 5834

    MDSGetServerListForUser = 5836
    MDSGetServerListForUserResponse = 5837

    MDSToCSFlushChunk = 5844

    MDSMigrateChunk = 5847
    MDSMigrateChunkResponse = 5848

    CSBase = 6200
    CSPing = 6201
    CSPingResponse = 6202

    GMSBase = 6400
    GMSGameServerReplicate = 6401
    ClientGMSServerQuery = 6403
    GMSClientServerQueryResponse = 6404
    AMGMSGameServerUpdate = 6405
    AMGMSGameServerRemove = 6406
    GameServerOutOfDate = 6407

    DeviceAuthorizationBase = 6500
    ClientAuthorizeLocalDeviceRequest = 6501

    ClientAuthorizeLocalDeviceResponse = 6502
    ClientDeauthorizeDeviceRequest = 6503
    ClientDeauthorizeDevice = 6504
    ClientUseLocalDeviceAuthorizations = 6505
    ClientGetAuthorizedDevices = 6506
    ClientGetAuthorizedDevicesResponse = 6507
    AMNotifySessionDeviceAuthorized = 6508
    ClientAuthorizeLocalDeviceNotification = 6509

    MMSBase = 6600
    ClientMMSCreateLobby = 6601
    ClientMMSCreateLobbyResponse = 6602
    ClientMMSJoinLobby = 6603
    ClientMMSJoinLobbyResponse = 6604
    ClientMMSLeaveLobby = 6605
    ClientMMSLeaveLobbyResponse = 6606
    ClientMMSGetLobbyList = 6607
    ClientMMSGetLobbyListResponse = 6608
    ClientMMSSetLobbyData = 6609
    ClientMMSSetLobbyDataResponse = 6610
    ClientMMSGetLobbyData = 6611
    ClientMMSLobbyData = 6612
    ClientMMSSendLobbyChatMsg = 6613
    ClientMMSLobbyChatMsg = 6614
    ClientMMSSetLobbyOwner = 6615
    ClientMMSSetLobbyOwnerResponse = 6616
    ClientMMSSetLobbyGameServer = 6617
    ClientMMSLobbyGameServerSet = 6618
    ClientMMSUserJoinedLobby = 6619
    ClientMMSUserLeftLobby = 6620
    ClientMMSInviteToLobby = 6621
    ClientMMSFlushFrenemyListCache = 6622
    ClientMMSFlushFrenemyListCacheResponse = 6623
    ClientMMSSetLobbyLinked = 6624

    NonStdMsgBase = 6800
    NonStdMsgMemcached = 6801
    NonStdMsgHTTPServer = 6802
    NonStdMsgHTTPClient = 6803
    NonStdMsgWGResponse = 6804
    NonStdMsgPHPSimulator = 6805
    NonStdMsgChase = 6806
    NonStdMsgDFSTransfer = 6807
    NonStdMsgTests = 6808
    NonStdMsgUMQpipeAAPL = 6809

    NonStdMsgLogsink = 6811
    NonStdMsgSteam2Emulator = 6812
    NonStdMsgRTMPServer = 6813

    UDSBase = 7000
    ClientUDSP2PSessionStarted = 7001
    ClientUDSP2PSessionEnded = 7002
    UDSRenderUserAuth = 7003
    UDSRenderUserAuthResponse = 7004
    ClientUDSInviteToGame = 7005

    UDSHasSession = 7006

    UDSHasSessionResponse = 7007

    MPASBase = 7100
    MPASVacBanReset = 7101

    KGSBase = 7200

    UCMBase = 7300
    ClientUCMAddScreenshot = 7301
    ClientUCMAddScreenshotResponse = 7302

    UCMResetCommunityContent = 7307
    UCMResetCommunityContentResponse = 7308
    ClientUCMDeleteScreenshot = 7309
    ClientUCMDeleteScreenshotResponse = 7310
    ClientUCMPublishFile = 7311
    ClientUCMPublishFileResponse = 7312

    ClientUCMDeletePublishedFile = 7315
    ClientUCMDeletePublishedFileResponse = 7316
    ClientUCMEnumerateUserPublishedFiles = 7317
    ClientUCMEnumerateUserPublishedFilesResponse = 7318

    ClientUCMEnumerateUserSubscribedFiles = 7321
    ClientUCMEnumerateUserSubscribedFilesResponse = 7322

    ClientUCMUpdatePublishedFile = 7325
    ClientUCMUpdatePublishedFileResponse = 7326
    UCMUpdatePublishedFile = 7327
    UCMUpdatePublishedFileResponse = 7328
    UCMDeletePublishedFile = 7329
    UCMDeletePublishedFileResponse = 7330
    UCMUpdatePublishedFileStat = 7331
    UCMUpdatePublishedFileBan = 7332
    UCMUpdatePublishedFileBanResponse = 7333

    UCMReloadPublishedFile = 7337
    UCMReloadUserFileListCaches = 7338
    UCMPublishedFileReported = 7339
    UCMUpdatePublishedFileIncompatibleStatus = 7340
    UCMPublishedFilePreviewAdd = 7341
    UCMPublishedFilePreviewAddResponse = 7342
    UCMPublishedFilePreviewRemove = 7343
    UCMPublishedFilePreviewRemoveResponse = 7344

    ClientUCMPublishedFileSubscribed = 7347
    ClientUCMPublishedFileUnsubscribed = 7348
    UCMPublishedFileSubscribed = 7349
    UCMPublishedFileUnsubscribed = 7350
    UCMPublishFile = 7351
    UCMPublishFileResponse = 7352
    UCMPublishedFileChildAdd = 7353
    UCMPublishedFileChildAddResponse = 7354
    UCMPublishedFileChildRemove = 7355
    UCMPublishedFileChildRemoveResponse = 7356

    UCMPublishedFileParentChanged = 7359

    UCMGetPublishedFilesForUser = 7362
    UCMGetPublishedFilesForUserResponse = 7363
    ClientUCMSetUserPublishedFileAction = 7364
    ClientUCMSetUserPublishedFileActionResponse = 7365
    ClientUCMEnumeratePublishedFilesByUserAction = 7366
    ClientUCMEnumeratePublishedFilesByUserActionResponse = 7367
    ClientUCMPublishedFileDeleted = 7368
    UCMGetUserSubscribedFiles = 7369
    UCMGetUserSubscribedFilesResponse = 7370
    UCMFixStatsPublishedFile = 7371

    ClientUCMEnumerateUserSubscribedFilesWithUpdates = 7378
    ClientUCMEnumerateUserSubscribedFilesWithUpdatesResponse = 7379
    UCMPublishedFileContentUpdated = 7380
    UCMPublishedFileUpdated = 7381
    ClientWorkshopItemChangesRequest = 7382
    ClientWorkshopItemChangesResponse = 7383
    ClientWorkshopItemInfoRequest = 7384
    ClientWorkshopItemInfoResponse = 7385

    FSBase = 7500
    ClientRichPresenceUpload = 7501
    ClientRichPresenceRequest = 7502
    ClientRichPresenceInfo = 7503
    FSRichPresenceRequest = 7504
    FSRichPresenceResponse = 7505
    FSComputeFrenematrix = 7506
    FSComputeFrenematrixResponse = 7507
    FSPlayStatusNotification = 7508
    FSPublishPersonaStatus = 7509
    FSAddOrRemoveFollower = 7510
    FSAddOrRemoveFollowerResponse = 7511
    FSUpdateFollowingList = 7512
    FSCommentNotification = 7513
    FSCommentNotificationViewed = 7514
    ClientFSGetFollowerCount = 7515
    ClientFSGetFollowerCountResponse = 7516
    ClientFSGetIsFollowing = 7517
    ClientFSGetIsFollowingResponse = 7518
    ClientFSEnumerateFollowingList = 7519
    ClientFSEnumerateFollowingListResponse = 7520
    FSGetPendingNotificationCount = 7521
    FSGetPendingNotificationCountResponse = 7522
    #   ClientFSOfflineMessageNotification = 7523 #: renamed
    #   ClientFSRequestOfflineMessageCount = 7524 #: renamed
    #   ClientFSGetFriendMessageHistory = 7525 #: renamed
    #   ClientFSGetFriendMessageHistoryResponse = 7526 #: renamed
    #   ClientFSGetFriendMessageHistoryForOfflineMessages = 7527 #: renamed
    ClientChatOfflineMessageNotification = 7523
    ClientChatRequestOfflineMessageCount = 7524
    ClientChatGetFriendMessageHistory = 7525
    ClientChatGetFriendMessageHistoryResponse = 7526
    ClientChatGetFriendMessageHistoryForOfflineMessages = 7527
    ClientFSGetFriendsSteamLevels = 7528
    ClientFSGetFriendsSteamLevelsResponse = 7529
    FSRequestFriendData = 7530

    DRMRange2 = 7600
    CEGVersionSetEnableDisableRequest = 7600
    CEGVersionSetEnableDisableResponse = 7601
    CEGPropStatusDRMSRequest = 7602
    CEGPropStatusDRMSResponse = 7603
    CEGWhackFailureReportRequest = 7604
    CEGWhackFailureReportResponse = 7605
    DRMSFetchVersionSet = 7606
    DRMSFetchVersionSetResponse = 7607

    EconBase = 7700
    EconTrading_InitiateTradeRequest = 7701
    EconTrading_InitiateTradeProposed = 7702
    EconTrading_InitiateTradeResponse = 7703
    EconTrading_InitiateTradeResult = 7704
    EconTrading_StartSession = 7705
    EconTrading_CancelTradeRequest = 7706
    EconFlushInventoryCache = 7707
    EconFlushInventoryCacheResponse = 7708
    EconCDKeyProcessTransaction = 7711
    EconCDKeyProcessTransactionResponse = 7712
    EconGetErrorLogs = 7713
    EconGetErrorLogsResponse = 7714

    RMRange = 7800
    RMTestVerisignOTP = 7800
    RMTestVerisignOTPResponse = 7801
    RMDeleteMemcachedKeys = 7803
    RMRemoteInvoke = 7804
    BadLoginIPList = 7805
    RMMsgTraceAddTrigger = 7806
    RMMsgTraceRemoveTrigger = 7807
    RMMsgTraceEvent = 7808

    UGSBase = 7900
    UGSUpdateGlobalStats = 7900
    ClientUGSGetGlobalStats = 7901
    ClientUGSGetGlobalStatsResponse = 7902

    StoreBase = 8000

    UMQBase = 8100
    UMQLogonRequest = 8100
    UMQLogonResponse = 8101
    UMQLogoffRequest = 8102
    UMQLogoffResponse = 8103
    UMQSendChatMessage = 8104
    UMQIncomingChatMessage = 8105
    UMQPoll = 8106
    UMQPollResults = 8107
    UMQ2AM_ClientMsgBatch = 8108

    WorkshopBase = 8200
    WorkshopAcceptTOSRequest = 8200
    WorkshopAcceptTOSResponse = 8201

    WebAPIBase = 8300
    WebAPIValidateOAuth2Token = 8300
    WebAPIValidateOAuth2TokenResponse = 8301

    WebAPIRegisterGCInterfaces = 8303
    WebAPIInvalidateOAuthClientCache = 8304
    WebAPIInvalidateOAuthTokenCache = 8305
    WebAPISetSecrets = 8306

    BackpackBase = 8400
    BackpackAddToCurrency = 8401
    BackpackAddToCurrencyResponse = 8402

    CREBase = 8500

    CREItemVoteSummary = 8503
    CREItemVoteSummaryResponse = 8504

    CREUpdateUserPublishedItemVote = 8507
    CREUpdateUserPublishedItemVoteResponse = 8508
    CREGetUserPublishedItemVoteDetails = 8509
    CREGetUserPublishedItemVoteDetailsResponse = 8510
    CREEnumeratePublishedFiles = 8511
    CREEnumeratePublishedFilesResponse = 8512
    CREPublishedFileVoteAdded = 8513

    SecretsBase = 8600
    SecretsRequestCredentialPair = 8600
    SecretsCredentialPairResponse = 8601

    BoxMonitorBase = 8700
    BoxMonitorReportRequest = 8700
    BoxMonitorReportResponse = 8701

    LogsinkBase = 8800
    LogsinkWriteReport = 8800

    PICSBase = 8900
    ClientPICSChangesSinceRequest = 8901
    ClientPICSChangesSinceResponse = 8902
    ClientPICSProductInfoRequest = 8903
    ClientPICSProductInfoResponse = 8904
    ClientPICSAccessTokenRequest = 8905
    ClientPICSAccessTokenResponse = 8906

    WorkerProcess = 9000
    WorkerProcessPingRequest = 9000
    WorkerProcessPingResponse = 9001
    WorkerProcessShutdown = 9002

    DRMWorkerProcess = 9100
    DRMWorkerProcessDRMAndSign = 9100
    DRMWorkerProcessDRMAndSignResponse = 9101
    DRMWorkerProcessSteamworksInfoRequest = 9102
    DRMWorkerProcessSteamworksInfoResponse = 9103
    DRMWorkerProcessInstallDRMDLLRequest = 9104
    DRMWorkerProcessInstallDRMDLLResponse = 9105
    DRMWorkerProcessSecretIdStringRequest = 9106
    DRMWorkerProcessSecretIdStringResponse = 9107

    DRMWorkerProcessInstallProcessedFilesRequest = 9110
    DRMWorkerProcessInstallProcessedFilesResponse = 9111
    DRMWorkerProcessExamineBlobRequest = 9112
    DRMWorkerProcessExamineBlobResponse = 9113
    DRMWorkerProcessDescribeSecretRequest = 9114
    DRMWorkerProcessDescribeSecretResponse = 9115
    DRMWorkerProcessBackfillOriginalRequest = 9116
    DRMWorkerProcessBackfillOriginalResponse = 9117
    DRMWorkerProcessValidateDRMDLLRequest = 9118
    DRMWorkerProcessValidateDRMDLLResponse = 9119
    DRMWorkerProcessValidateFileRequest = 9120
    DRMWorkerProcessValidateFileResponse = 9121
    DRMWorkerProcessSplitAndInstallRequest = 9122
    DRMWorkerProcessSplitAndInstallResponse = 9123
    DRMWorkerProcessGetBlobRequest = 9124
    DRMWorkerProcessGetBlobResponse = 9125
    DRMWorkerProcessEvaluateCrashRequest = 9126
    DRMWorkerProcessEvaluateCrashResponse = 9127
    DRMWorkerProcessAnalyzeFileRequest = 9128
    DRMWorkerProcessAnalyzeFileResponse = 9129
    DRMWorkerProcessUnpackBlobRequest = 9130
    DRMWorkerProcessUnpackBlobResponse = 9131
    DRMWorkerProcessInstallAllRequest = 9132
    DRMWorkerProcessInstallAllResponse = 9133

    TestWorkerProcess = 9200
    TestWorkerProcessLoadUnloadModuleRequest = 9200
    TestWorkerProcessLoadUnloadModuleResponse = 9201
    TestWorkerProcessServiceModuleCallRequest = 9202
    TestWorkerProcessServiceModuleCallResponse = 9203

    QuestServerBase = 9300

    ClientGetEmoticonList = 9330
    ClientEmoticonList = 9331

    SLCBase = 9400
    SLCUserSessionStatus = 9400
    SLCRequestUserSessionStatus = 9401
    SLCSharedLicensesLockStatus = 9402

    ClientSharedLibraryLockStatus = 9405
    ClientSharedLibraryStopPlaying = 9406
    SLCOwnerLibraryChanged = 9407
    SLCSharedLibraryChanged = 9408

    RemoteClientBase = 9500
    RemoteClientAuth = 9500
    RemoteClientAuthResponse = 9501
    RemoteClientAppStatus = 9502
    RemoteClientStartStream = 9503
    RemoteClientStartStreamResponse = 9504
    RemoteClientPing = 9505
    RemoteClientPingResponse = 9506
    ClientUnlockStreaming = 9507
    ClientUnlockStreamingResponse = 9508
    RemoteClientAcceptEULA = 9509
    RemoteClientGetControllerConfig = 9510
    RemoteClientGetControllerConfigResposne = 9511
    RemoteClientStreamingEnabled = 9512
    ClientUnlockHEVC = 9513
    ClientUnlockHEVCResponse = 9514

    ClientConcurrentSessionsBase = 9600
    ClientKickPlayingSession = 9601

    ClientBroadcastBase = 9700
    ClientBroadcastFrames = 9701
    ClientBroadcastDisconnect = 9702
    ClientBroadcastScreenshot = 9703
    ClientBroadcastUploadConfig = 9704

    BaseClient3 = 9800
    ClientVoiceCallPreAuthorizeResponse = 9801
    ClientServerTimestampRequest = 9802
