# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: steammessages_unified_base.steamworkssdk.proto
# plugin: python-betterproto

import betterproto


class EProtoExecutionSite(betterproto.Enum):
    k_EProtoExecutionSiteUnknown = 0
    k_EProtoExecutionSiteSteamClient = 3
