name: Automatically build documentation for documetation PRs.

on: [pull_request]

jobs:
  build-documentation:
    if: ${{
        startsWith(github.event.pull_request.title, '[docs]') ||
        startsWith(github.event.pull_request.title, '[RFC]') ||
        contains(github.event.pull_request.title, 'Add') ||
        contains(github.event.pull_request.title, 'Implement')
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Comment with documentation link
        uses: mb2dev/github-action-comment-pull-request
        with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           message: |
            @${{ github.event.pull_request.author.login }} Hello there! :wave:

            Built documentation for this pull request can be found at https://steampy--{{ github.event.pull_request.number }}.org.readthedocs.build/en/{{ github.event.pull_request.number }}
