name: Automatically comment with a documentation link for documetation PRs.

on:
  pull_request:
    types: [opened]

jobs:
  comment-with-documentation-url:
    if: ${{
      startsWith(github.event.pull_request.title, '[docs]') ||
      startsWith(github.event.pull_request.title, '[RFC]') ||
      contains(github.event.pull_request.title, 'Add') ||
      contains(github.event.pull_request.title, 'Implement')
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Comment with documentation link
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello there! :wave:

            Built documentation for this pull request can be found at https://steampy--${{ github.event.pull_request.number }}.org.readthedocs.build/en/${{ github.event.pull_request.number }}
