# This workflow will check any code for Exceptions or other inconsistencies in code.

name: Lint Python.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  lint_python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install flake8
      - run: |
          flake8 . --count --select=E9,F63,F7,F82,F632,E0401 --max-line-length=120 --show-source --statistics
